PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS questions(id INTEGER PRIMARY KEY,public_id TEXT UNIQUE,marketplace TEXT NOT NULL,external_question_id TEXT NOT NULL,product_id TEXT,product_article TEXT,product_title TEXT,question_text TEXT NOT NULL,question_created_at TEXT,raw_status TEXT,status TEXT NOT NULL DEFAULT 'NEW',current_answer_revision_id INTEGER,current_draft_attempt_id INTEGER,telegram_question_message_id INTEGER,telegram_current_message_id INTEGER,external_reply_id TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,sent_at TEXT,UNIQUE(marketplace,external_question_id));
CREATE TABLE IF NOT EXISTS answer_revisions(id INTEGER PRIMARY KEY,question_id INTEGER NOT NULL REFERENCES questions(id),source TEXT NOT NULL,text TEXT NOT NULL,draft_attempt_id INTEGER,based_on_revision_id INTEGER,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS draft_attempts(id INTEGER PRIMARY KEY,question_id INTEGER NOT NULL REFERENCES questions(id),codex_profile TEXT NOT NULL,status TEXT NOT NULL,answer_text TEXT,error_type TEXT,error_message TEXT,started_at TEXT NOT NULL,finished_at TEXT);
CREATE TABLE IF NOT EXISTS telegram_inputs(telegram_prompt_message_id INTEGER PRIMARY KEY,question_id INTEGER NOT NULL REFERENCES questions(id),mode TEXT NOT NULL,based_on_revision_id INTEGER,created_at TEXT NOT NULL,expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS telegram_updates(update_id INTEGER PRIMARY KEY,update_json TEXT NOT NULL,received_at TEXT NOT NULL,completed_at TEXT);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS recent_errors(id INTEGER PRIMARY KEY,component TEXT,error_type TEXT,message TEXT,question_id INTEGER,fingerprint TEXT UNIQUE,first_seen_at TEXT,last_seen_at TEXT,occurrence_count INTEGER,telegram_notified_at TEXT);
CREATE TABLE IF NOT EXISTS telegram_delivery_failures(question_id INTEGER NOT NULL REFERENCES questions(id),operation TEXT NOT NULL,outcome TEXT NOT NULL,message_id INTEGER,detail TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(question_id,operation));
