import assert from 'node:assert/strict';
import {runtime, seedFiles, file, info, help, provider, copy, CONV} from './harness.mjs';
import {createHash} from 'node:crypto';
const dist=process.argv[2];if(!dist)throw Error('dist path required');
const REF1='rpf_s_00000000-0000-4000-8000-000000000001',REF2='rpf_s_00000000-0000-4000-8000-000000000002';
let count=0;
async function test(name,fn){try{await fn();count++;console.log('PASS',name);}catch(e){console.error('FAIL',name);throw e;}}
function make(options={}) {const w=runtime(dist,{fetchImpl:provider,...options});w.seed();seedFiles(w);return w;}
const entries=o=>o.batch.entries;
const env=e=>JSON.parse(e.report_text.slice('OZON_RESULT_V1\n'.length));
async function commit(w,o,kind='manual'){const c=await w.port('OZ_ATTACHMENT_COMMIT',w.payload(o,kind));assert.equal(c.ok,true,JSON.stringify(c));assert.equal(c.attach_allowed,true,JSON.stringify(c));return c.recovery;}
async function finish(w,o,kind='manual') {const p=w.payload(o,kind);for(const type of ['OZ_ATTACHMENT_READY','OZ_ATTACHMENT_SEND_COMMIT','OZ_ATTACHMENT_CONFIRM']){const r=await w.port(type,{...p,attached_filenames:['f'],confirmed_user_turn_id:'u-fixture'});assert.equal(r.ok,true,JSON.stringify(r));} }
for(const kind of ['manual','autorun']) {
 await test(kind+' Alice original + info + HELP: one attachment plus EXACT full text',async()=>{const w=make();if(kind==='autorun')w.seed(kind);const o=await w.batch([file(),info,help],kind);assert.equal(w.requests.length,2);assert.equal(entries(o).length,3);assert.equal(o.delivery.generated_text_document,null);const r=await commit(w,o,kind);assert.equal(r.artifact_descriptors.length,1);assert.ok(r.outgoing_text.endsWith(o.delivery.inline_result_text));assert.ok(r.outgoing_text.includes('OZON_GUIDANCE_RESULT_V2'));assert.ok(r.outgoing_text.includes('OZON_LLM_INSTRUCTIONS_V1'));await finish(w,o,kind);});
 await test(kind+' Alice second original deferred BEFORE fetch; info/HELP retained',async()=>{const w=make();if(kind==='autorun')w.seed(kind);const o=await w.batch([file(),file(REF2),info,help],kind);assert.equal(w.requests.length,2);const second=env(entries(o)[1]);assert.equal(second.http_status,0);assert.equal(second.request_meta.external_request_executed,false);assert.equal(second.result.delivery.state,'deferred');assert.deepEqual(second.result.delivery.next_command,file(REF2));const r=await commit(w,o,kind);assert.equal(r.artifact_descriptors.length,1);assert.ok(r.outgoing_text.includes('TARGET_AI_FILE_LIMIT'));const x=w.context.OzonLlmOutputReportWorkflowPatch.instructionPayload(o.delivery.inline_result_text);assert.ok(x.workflow_continuations.some(c=>c.state==='deferred'&&c.next_command.params.file_ref===REF2));assert.equal(w.context.safeBatchQueryPlannerSummary(o.batch,entries(o)).physical_business_request_count,2);});
}
await test('ChatGPT two originals unchanged: two fetches two original attachments',async()=>{const w=make({adapter:'chatgpt'});const o=await w.batch([file(),file(REF2)]);assert.equal(w.requests.length,2);const r=await commit(w,o);assert.equal(r.artifact_descriptors.length,2);assert.ok(r.artifact_descriptors.every(x=>x.source_kind==='original_provider_file'));});
await test('ChatGPT mixed original/text still retains previous companion policy',async()=>{const w=make({adapter:'chatgpt'});const o=await w.batch([file(),info,help]);assert.equal(w.requests.length,2);assert.equal(o.delivery.generated_text_document.extension,'txt');const r=await commit(w,o);assert.equal(r.artifact_descriptors.length,2);});
await test('Alice pre-attachment error yields existing text delivery with complete results',async()=>{const w=make();const o=await w.batch([file(),info,help]);const r=await w.port('OZ_ATTACHMENT_FAIL',{...w.payload(o),code:'TARGET_AI_ATTACHMENT_SURFACE_UNAVAILABLE',error:'not forwarded raw'});assert.equal(r.text_fallback,true,JSON.stringify(r));assert.ok(w.owner().batch);assert.equal(w.owner().delivery.mode,'batch_watch_v1');assert.ok(w.owner().delivery.outgoing_text.endsWith(o.delivery.inline_result_text));assert.ok(w.owner().delivery.outgoing_text.includes('TARGET_AI_ATTACHMENT_SURFACE_UNAVAILABLE'));assert.ok(!w.owner().delivery.outgoing_text.includes('not forwarded raw'));assert.ok(w.pushes.some(m=>m.type==='OZ_BATCH_DELIVERY_AVAILABLE'&&m.recovery.outgoing_text.includes('TEXT_DELIVERY_FAILURE_RECEIPT')));assert.equal(w.requests.length,2);});
await test('Alice post-commit unknown outcome cannot fallback/resend',async()=>{const w=make();const o=await w.batch([file(),info]);await commit(w,o);const n=w.pushes.filter(x=>x.type==='OZ_BATCH_DELIVERY_AVAILABLE').length;const r=await w.port('OZ_ATTACHMENT_FAIL',{...w.payload(o),code:'ATTACH_OUTCOME_UNKNOWN_NO_RETRY'});assert.equal(r.text_fallback,undefined);assert.equal(w.pushes.filter(x=>x.type==='OZ_BATCH_DELIVERY_AVAILABLE').length,n);assert.equal(w.requests.length,2);});
await test('First file HTTP403 frees slot for second; error retained and no retry',async()=>{let n=0;const w=make({fetchImpl:async(u,i)=>String(u).includes('fixture-0')?new Response('forbidden',{status:403,headers:{'content-type':'text/plain'}}):provider(u,i)});const o=await w.batch([file(),file(REF2),help]);assert.equal(w.requests.length,2);assert.equal(entries(o)[0].http_status,403);assert.equal(entries(o)[1].http_status,200);const r=await commit(w,o);assert.equal(r.artifact_descriptors.length,1);assert.ok(r.outgoing_text.includes('"http_status": 403'));});
await test('PolicyOFF before budget: personal file blocked, safe file proceeds',async()=>{const w=make();const p='rpf_p_00000000-0000-4000-8000-000000000003';seedFiles(w,[REF1,p]);const o=await w.batch([file(p),file(REF1)]);assert.equal(w.requests.length,1);assert.equal(entries(o)[0].kind,'policy_error');assert.equal(entries(o)[1].http_status,200);await commit(w,o);});
await test('One file only still has one attachment and real original bytes',async()=>{const w=make();const o=await w.batch([file()]);const r=await commit(w,o);const d=r.artifact_descriptors[0],a=w.artifacts.get(d.artifact_key);assert.equal(d.sha256,createHash('sha256').update(Buffer.from(a.bytes)).digest('hex'));assert.equal(Buffer.from(a.bytes).toString(),'sku;qty\n111;3\n');});
await test('Duplicate file command is deferred, no hidden redundant download',async()=>{const w=make();const o=await w.batch([file(),file()]);assert.equal(w.requests.length,1);assert.equal(env(entries(o)[1]).result.delivery.state,'deferred');await commit(w,o);});
async function large() {const w=make({fetchImpl:async(u,i)=>String(u).includes('/report/info')?new Response(JSON.stringify({result:{code:'REPORT_FIXTURE',status:'processing',note:'X'.repeat(95000)}}),{headers:{'content-type':'application/json'}}):provider(u,i)});const o=await w.batch([file(),info]);assert.ok(o.delivery.inline_result_text.length>90000);const r=await commit(w,o);return {w,o,r};}
await test('True text overflow: first original + bounded notice; exact full TXT durably retained',async()=>{const{w,o,r}=await large();assert.equal(r.artifact_descriptors.length,1);assert.ok(r.outgoing_text.length<=90000);assert.ok(r.outgoing_text.includes('TARGET_AI_TEXT_CAPACITY'));const a=w.artifacts.get('provider:'+o.delivery.retained_text_ref);assert.equal(a.source_kind,'generated_bridge_text');assert.equal(Buffer.from(a.bytes).toString(),o.delivery.inline_result_text);assert.equal(w.requests.length,2);});
await test('Retained TXT survives confirmation + worker recreation; explicit next get is local HTTP0',async()=>{const{w,o,r}=await large();const ref=o.delivery.retained_text_ref;const saved=Buffer.from(w.artifacts.get('provider:'+ref).bytes);await finish(w,o);assert.ok(w.artifacts.has('provider:'+ref));const w2=runtime(dist,{store:w.store,sessionStore:w.sessionStore,artifacts:w.artifacts,clock:w.clock,fetchImpl:provider});const next=await w2.batch([file(ref)]);assert.equal(w2.requests.length,0);assert.equal(entries(next)[0].http_status,0);assert.equal(env(entries(next)[0]).result.delivery.state,'local_file_ready');const r2=await commit(w2,next);assert.equal(r2.artifact_descriptors.length,1);assert.equal(r2.artifact_descriptors[0].source_kind,'generated_bridge_text');assert.deepEqual(Buffer.from(w2.artifacts.get('provider:'+ref).bytes),saved);assert.ok(r2.outgoing_text.length<90000);await finish(w2,next);});
for(const [name,mutate] of [
 ['wrong conversation',(w,a)=>{a.local_delivery.conversation_key='other';}],
 ['wrong origin',(w,a)=>{a.local_delivery.origin='https://evil.invalid';}],
 ['changed credentials',(w,a)=>{w.store.ozmb_seller_api_key='different-fixture-only';}],
 ['expired',(w,a)=>{a.expires_at_ms=w.clock.now-1;}],
 ['corrupt hash',(w,a)=>{a.sha256='0'.repeat(64);}],
 ['wrong byte length',(w,a)=>{a.byte_length++;}],
 ['wrong type',(w,a)=>{a.extension='xlsx';}],
]) await test('Retained TXT '+name+' rejected locally without provider',async()=>{const{w,o}=await large();const ref=o.delivery.retained_text_ref;await finish(w,o);mutate(w,w.artifacts.get('provider:'+ref));const w2=runtime(dist,{store:w.store,sessionStore:w.sessionStore,artifacts:w.artifacts,clock:w.clock,fetchImpl:provider});const n=await w2.batch([file(ref)]);assert.equal(w2.requests.length,0);assert.equal(env(entries(n)[0]).result.delivery.state,'blocked');});

await test('Pending local file with missing IDB bytes cannot fall through to an Ozon URL',async()=>{const w=make();const ref='rpf_s_local_00000000-0000-4000-8000-000000000099';seedFiles(w,[ref]);const o=await w.batch([file(ref)]);assert.equal(w.requests.length,0);assert.equal(env(entries(o)[0]).result.delivery.reason,'LOCAL_DELIVERY_NOT_FOUND');});
await test('Retained TXT modified offset rejected: do not silently reinterpret the explicit command',async()=>{const{w,o}=await large();const ref=o.delivery.retained_text_ref;await finish(w,o);const n=await w.batch([{...file(ref),params:{...file(ref).params,offset:1}}]);assert.equal(w.requests.length,2);assert.equal(env(entries(n)[0]).result.delivery.reason,'LOCAL_DELIVERY_COMMAND_MISMATCH');});
await test('Retained private TXT blocked when personal-data switch is turned OFF',async()=>{const w=make({fetchImpl:async(u,i)=>String(u).includes('/report/info')?new Response(JSON.stringify({result:{status:'processing',note:'X'.repeat(95000)}}),{headers:{'content-type':'application/json'}}):provider(u,i)});w.store.ozmb_personal_data_enabled_v1=true;const o=await w.batch([file(),info]);const r=await commit(w,o);assert.ok(o.delivery.retained_text_ref.startsWith('rpf_p_local_'));await finish(w,o);w.store.ozmb_personal_data_enabled_v1=false;const n=await w.batch([file(o.delivery.retained_text_ref)]);assert.equal(entries(n)[0].kind,'policy_error');assert.equal(w.requests.length,2);});
await test('Retained artifact scope rechecked at attachment, not only at earlier read',async()=>{const{w,o}=await large();await finish(w,o);const n=await w.batch([file(o.delivery.retained_text_ref)]);w.store.ozmb_seller_api_key='changed-after-local-read';const c=await w.port('OZ_ATTACHMENT_COMMIT',w.payload(n));assert.equal(c.ok,false);assert.equal(c.code,'LOCAL_DELIVERY_SCOPE_MISMATCH');assert.equal(w.requests.length,2);});
await test('Foreign conversation/tab cannot trigger precommit text fallback',async()=>{const w=make();const o=await w.batch([file(),info]);const p=w.payload(o);const n=w.pushes.length;const c=await w.port('OZ_ATTACHMENT_FAIL',{...p,code:'TEST'},{url:w.origin+'/chat/'+CONV,tab:{id:999,url:w.origin+'/chat/'+CONV}});assert.equal(c.ok,false);assert.equal(w.owner().delivery.mode,'attachment_watch_v1');assert.equal(w.pushes.length,n);});
await test('Stale delivery ID cannot trigger fallback in the new active owner',async()=>{const w=make();const o=await w.batch([file(),info]);const c=await w.port('OZ_ATTACHMENT_FAIL',{...w.payload(o),delivery_id:'foreign-delivery',code:'TEST'});assert.equal(c.ok,false);assert.equal(w.owner().delivery.mode,'attachment_watch_v1');});
await test('Concurrent precommit fallback grants exactly one text handover',async()=>{const w=make();const o=await w.batch([file(),info]);const before=w.pushes.filter(x=>x.type==='OZ_BATCH_DELIVERY_AVAILABLE').length;const p={...w.payload(o),code:'TEST'};const both=await Promise.all([w.port('OZ_ATTACHMENT_FAIL',p),w.port('OZ_ATTACHMENT_FAIL',p)]);assert.equal(both.filter(x=>x.text_fallback).length,1);assert.equal(w.pushes.filter(x=>x.type==='OZ_BATCH_DELIVERY_AVAILABLE').length,before+1);assert.equal(w.owner().delivery.mode,'batch_watch_v1');});
await test('Concurrent attachment commits grant one attach; retention deadline never renewed',async()=>{const w=make({fetchImpl:async(u,i)=>String(u).includes('/report/info')?new Response(JSON.stringify({result:{status:'processing',note:'X'.repeat(95000)}}),{headers:{'content-type':'application/json'}}):provider(u,i)});const o=await w.batch([file(),info]);const both=await Promise.all([w.port('OZ_ATTACHMENT_COMMIT',w.payload(o)),w.port('OZ_ATTACHMENT_COMMIT',w.payload(o))]);assert.equal(both.filter(x=>x.attach_allowed).length,1);const a=w.artifacts.get('provider:'+o.delivery.retained_text_ref);assert.equal(a.expires_at_ms,Date.parse(o.delivery.claimed_at)+3600000);assert.equal(w.requests.length,2);});
await test('Pure HELP and short JSON keep text delivery (no attachment budget applied)',async()=>{const w=make();const o=await w.batch([info,help,help]);assert.equal(o.delivery.mode,'batch_watch_v1');assert.equal(w.requests.length,1);assert.equal(entries(o).length,3);});
await test('Pure oversized text keeps one original generated TXT path',async()=>{const w=make({fetchImpl:async()=>new Response(JSON.stringify({result:{status:'processing',note:'X'.repeat(95000)}}),{headers:{'content-type':'application/json'}})});const o=await w.batch([info]);assert.equal(o.delivery.generated_text_document.extension,'txt');const r=await commit(w,o);assert.equal(r.artifact_descriptors.length,1);assert.equal(r.artifact_descriptors[0].source_kind,'generated_bridge_text');});
await test('File result after text/HELP: no spurious consumption of budget',async()=>{const w=make();const o=await w.batch([help,info,file(),file(REF2)]);assert.equal(w.requests.length,2);assert.equal(entries(o)[2].http_status,200);assert.equal(env(entries(o)[3]).result.delivery.state,'deferred');await commit(w,o);});
await test('Three files: two explicit local deferrals; one physical request and receipt partial=false is forbidden',async()=>{const w=make();const third='rpf_s_00000000-0000-4000-8000-000000000003';seedFiles(w,[REF1,REF2,third]);const o=await w.batch([file(),file(REF2),file(third)]);assert.equal(w.requests.length,1);const r=await commit(w,o);const m=JSON.parse(r.outgoing_text.split('\n\n')[0].slice('OZON_BATCH_RESULT_V1\n'.length));assert.equal(m.complete,false);assert.equal(m.deferred_file_count,2);assert.equal(r.artifact_descriptors.length,1);});
await test('Budget resumes from durable first completed file after worker recreation',async()=>{const w=make();const o=await w.batch([file(),file(REF2),info,help]);const paused=copy(o);paused.status='requesting';paused.delivery=null;paused.batch.phase='collecting';paused.batch.next_index=1;paused.batch.entries=[entries(o)[0],...copy(w.context.discoverBatchEntries('OZON_API_V1\n'+JSON.stringify(file(REF2))+'\nOZON_API_V1\n'+JSON.stringify(info)+'\nOZON_HELP_V2\n'+JSON.stringify(help.help)))];w.store.ozmb_manual_operations[w.key]=paused;const w2=runtime(dist,{store:w.store,sessionStore:w.sessionStore,artifacts:w.artifacts,clock:w.clock,fetchImpl:provider});await w2.context.processManualBatch(w2.key,paused.operation_id);const n=w2.owner();assert.equal(n.status,'delivering');assert.equal(w2.requests.length,1);assert.ok(w2.requests[0].url.includes('/report/info'));assert.equal(env(entries(n)[1]).result.delivery.state,'deferred');const r=await commit(w2,n);assert.equal(r.artifact_descriptors.length,1);});
await test('In-flight request after recreation remains unknown; no capacity repair may retry it',async()=>{const w=make();const o=await w.batch([file(),file(REF2)]);const paused=copy(o);paused.status='requesting';paused.delivery=null;paused.batch.next_index=1;paused.batch.entries[1]={...copy(w.context.discoverBatchEntries('OZON_API_V1\n'+JSON.stringify(file(REF2)))[0]),status:'requesting'};paused.batch.request_state='requesting';paused.batch.request_worker_session_id='old-dead-worker';w.store.ozmb_manual_operations[w.key]=paused;const w2=runtime(dist,{store:w.store,sessionStore:w.sessionStore,artifacts:w.artifacts,clock:w.clock,fetchImpl:provider});await w2.context.processManualBatch(w2.key,paused.operation_id);assert.equal(w2.requests.length,0);assert.equal(w2.owner().last_error.code,'REQUEST_OUTCOME_UNKNOWN_NO_RETRY');});
await test('Deferred command becomes executable in next explicit turn, no hidden continuation',async()=>{const w=make();const o=await w.batch([file(),file(REF2)]);await commit(w,o);await finish(w,o);assert.equal(w.requests.length,1);const next=env(entries(o)[1]).result.delivery.next_command;const n=await w.batch([next]);assert.equal(w.requests.length,2);assert.equal(entries(n)[0].http_status,200);await commit(w,n);});
await test('Expired deferred original does not extend URL or fabricate state on next turn',async()=>{const w=make();const o=await w.batch([file(),file(REF2)]);await commit(w,o);await finish(w,o);w.clock.now+=1800001;const n=await w.batch([env(entries(o)[1]).result.delivery.next_command]);assert.equal(w.requests.length,1);assert.equal(entries(n)[0].http_status,0);assert.ok(entries(n)[0].report_text.includes('REPORT_FILE_REF_NOT_FOUND'));});
await test('Unavailable artifact store for ordinary original does NOT prevent original provider execution',async()=>{const w=make();w.faults.open=true;const o=await w.batch([file()]);assert.equal(w.requests.length,1);assert.equal(entries(o)[0].http_status,200);const c=await w.port('OZ_ATTACHMENT_COMMIT',w.payload(o));assert.equal(c.ok,false);const r=await w.port('OZ_ATTACHMENT_FAIL',{...w.payload(o),code:c.code});assert.equal(r.text_fallback,true);assert.equal(w.requests.length,1);});
await test('Oversized precommit storage failure retains whole result and sends honest bounded notice',async()=>{const w=make({fetchImpl:async(u,i)=>String(u).includes('/report/info')?new Response(JSON.stringify({result:{status:'processing',note:'X'.repeat(95000)}}),{headers:{'content-type':'application/json'}}):provider(u,i)});const o=await w.batch([file(),info]);w.faults.put=true;const c=await w.port('OZ_ATTACHMENT_COMMIT',w.payload(o));assert.equal(c.ok,false);const f=await w.port('OZ_ATTACHMENT_FAIL',{...w.payload(o),code:c.code});assert.equal(f.text_fallback,true);assert.equal(w.owner().retained_delivery_failure.text,o.delivery.inline_result_text);assert.ok(w.owner().delivery.outgoing_text.length<90000);assert.ok(w.owner().delivery.outgoing_text.includes('"complete":false'));assert.equal(w.requests.length,2);});
// Every registry-classified binary route, not a hand-picked alias list.
{
 const sample=make();
 const binary=Object.entries(sample.context.OzonOperationRegistry.OPERATIONS).filter(([k,m])=>m.execution_enabled&&m.response_style==='binary');
 assert.equal(binary.length,11,'review the registry binary closed set if it changes');
 for(const[alias,meta]of binary)await test('Budget covers registry binary route '+alias,async()=>{
  const type=meta.response_content_types[0];
  const body=type==='application/pdf'?Buffer.from('%PDF-1.4\n%%EOF\n'):type==='image/png'?Buffer.from([137,80,78,71,13,10,26,10,0]):Buffer.from('sku;qty\n111;3\n');
  const w=make({fetchImpl:async(u,i)=>String(u).endsWith('/api/client/token')?new Response(JSON.stringify({access_token:'fixture-token',expires_in:3600}),{headers:{'content-type':'application/json'}}):String(u).includes('/report/info')?provider(u,i):new Response(body,{headers:{'content-type':type}})});
  w.store.ozmb_personal_data_enabled_v1=true;w.store.ozmb_performance_client_id='fixture-client';w.store.ozmb_performance_client_secret='fixture-secret';
  const cmd=copy(meta.template);assert.ok(cmd,alias+' needs explicit offline fixture');if(cmd.params.dateFrom){cmd.params.dateFrom='2026-09-01';cmd.params.dateTo='2026-09-02';}
  const o=await w.batch([cmd,file()]);assert.equal(entries(o)[0].http_status,200,entries(o)[0].report_text);assert.equal(env(entries(o)[1]).result.delivery.state,'deferred');assert.equal(w.requests.filter(x=>!x.url.endsWith('/api/client/token')).length,1);if(o.delivery.mode==='attachment_watch_v1'){const r=await commit(w,o);assert.equal(r.artifact_descriptors.length,1);}else {assert.equal(type,'application/pdf');const first=env(entries(o)[0]);assert.ok(first.result.generated_file_ref);assert.equal(first.result.generated_file_inline,undefined);assert.ok(o.delivery.outgoing_text.includes('report_file_get'));}
 });
}

for(const delta of [0,1])await test('Alice final marker+body exact 90000 UTF16 boundary delta='+delta,async()=>{const probe=make();const p=await probe.batch([file()]);const pc=await commit(probe,p);const markerLength=pc.outgoing_text.length-p.delivery.inline_result_text.length-2;const w=make();const o=await w.batch([file()]);const text='Z'.repeat(90000-markerLength-2+delta);w.owner().delivery.inline_result_text=text;const r=await commit(w,w.owner());if(delta===0){assert.equal(r.outgoing_text.length,90000);assert.ok(r.outgoing_text.endsWith(text));assert.ok(!r.outgoing_text.includes('full_text_deferred'));}else{assert.ok(r.outgoing_text.length<90000);assert.ok(r.outgoing_text.includes('full_text_deferred'));assert.equal(Buffer.from(w.artifacts.get('provider:'+o.delivery.retained_text_ref).bytes).toString(),text);}});
await test('Alice uses UTF16, not code points, for supplementary-plane text overflow',async()=>{const w=make();const o=await w.batch([file()]);w.owner().delivery.inline_result_text='😀'.repeat(45000);const r=await commit(w,w.owner());assert.ok(r.outgoing_text.includes('full_text_deferred'));assert.equal(Buffer.from(w.artifacts.get('provider:'+o.delivery.retained_text_ref).bytes).toString(),'😀'.repeat(45000));});
await test('Deferred complete text must not falsely acknowledge a report-prefix delivery',async()=>{const w=make();const o=await w.batch([file()]);w.owner().delivery.inline_result_text='PREFIX SENT LATER\n'+'X'.repeat(95000);w.owner().delivery.report_prefix_applied=true;const r=await commit(w,w.owner());assert.equal(w.owner().delivery.report_prefix_applied,false);assert.equal(r.artifact_descriptors.length,1);});
await test('Retained deadline check independent of background cleanup',async()=>{const{w,o}=await large();const ref=o.delivery.retained_text_ref;const a=w.artifacts.get('provider:'+ref);w.clock.now=a.expires_at_ms;await assert.rejects(()=>w.context.OzonFileDeliveryWorker.readRetainedText(w.into(o),w.into(file(ref))),e=>e.code==='LOCAL_DELIVERY_EXPIRED');assert.ok(w.artifacts.has('provider:'+ref));});
await test('Retained TXT JSON key permutation survives storage and keeps semantic guard',async()=>{const{w,o}=await large();const ref=o.delivery.retained_text_ref;await finish(w,o);const w2=runtime(dist,{store:w.store,sessionStore:w.sessionStore,artifacts:w.artifacts,clock:w.clock,fetchImpl:provider});const n=await w2.batch([{params:{limit:200,offset:0,file_ref:ref},operation:'report_file_get'}]);assert.equal(w2.requests.length,0);assert.equal(env(entries(n)[0]).result.delivery.state,'local_file_ready',entries(n)[0].report_text);const r=await commit(w2,n);assert.equal(r.artifact_descriptors.length,1);assert.equal(r.artifact_descriptors[0].source_kind,'generated_bridge_text');});
console.log(JSON.stringify({status:'PASS',cases:count,provider_calls:0}));
