import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import path from 'node:path';
import {pathToFileURL as U} from 'node:url';
const root=path.resolve(process.argv[2]), swaggerPath=process.argv[3]?path.resolve(process.argv[3]):null;
const load=n=>import(U(path.join(root,'shared',n)).href+`?b46=${Date.now()}${n}`);
for(const n of ['runtime_names.js','ozon_operation_registry.js','ozon_entitlements.js','ozon_contract.js','ozon_guidance.js']) await load(n);
const R=globalThis.OzonOperationRegistry,E=globalThis.OzonEntitlements,C=globalThis.OzonContract,G=globalThis.OzonGuidance; assert(R&&E&&C&&G);
const operation='posting_fbs_cancel_reason', apiPath='/v1/posting/fbs/cancel-reason', meta=R.OPERATIONS[operation]; assert(meta);
for(const[k,v]of Object.entries({provider:'seller_api',method:'POST',path:apiPath,effect:'READ',request_style:'json_body',execution_enabled:true,currentness:'current',safety_class:'READ_SAFE',privacy_policy:'safe_projection',cluster:'returns_cancellations',section:'cancellations',guidance_visibility:'user',entitlement_key:`POST ${apiPath}`,workflow_role:'single_read'})) assert.deepEqual(meta[k],v,`${operation}.${k}`);
assert.equal(R.catalogValidation(C.OPERATIONS).ok,true); console.log('B46_FBS_POSTING_CANCEL_REASON_REGISTRY_PASS');
let r=C.buildRequest(C.normalizeCommand({operation,params:{related_posting_numbers:['12345678-0001-1','']}}),{}); assert.equal(r.url,'https://api-seller.ozon.ru/v1/posting/fbs/cancel-reason'); assert.equal(r.method,'POST'); assert.deepEqual(JSON.parse(r.body),{related_posting_numbers:['12345678-0001-1','']});
r=C.buildRequest(C.normalizeCommand({operation,params:{related_posting_numbers:[]}}),{}); assert.deepEqual(JSON.parse(r.body),{related_posting_numbers:[]});
const bad=(p,c='INVALID_OPERATION_PARAMS')=>assert.throws(()=>C.normalizeCommand({operation,params:p}),e=>e?.code===c);
bad({}); bad({related_posting_numbers:'x'}); bad({related_posting_numbers:[1]}); bad({related_posting_numbers:['x'],url:'https://evil.example'},'TRANSPORT_INJECTION_REJECTED'); bad({related_posting_numbers:['x'],headers:{x:'y'}},'TRANSPORT_INJECTION_REJECTED'); console.log('B46_FBS_POSTING_CANCEL_REASON_EXACT_REQUEST_CONTRACT_PASS');
const q=E.requirementFor(C.normalizeCommand(meta.template)), pl=C.planCommandForSellerCapability(C.normalizeCommand(meta.template),null); assert.equal(q.known,true); assert.equal(q.required,false); assert.equal(q.default_access,'ALL_ACCOUNTS'); assert.equal(pl.action,'execute'); console.log('B46_FBS_POSTING_CANCEL_REASON_ENTITLEMENT_PASS');
const gd=G.result({status:'guidance',cluster:'returns_cancellations',section:'cancellations',version:2}); assert(gd.choices.some(x=>x.operation===operation)); assert.equal(gd.physical_business_request_count,0); assert.equal(gd.external_request_executed,false); console.log('B46_GUIDANCE_ZERO_REQUEST_PASS');
const clean=C.sanitizeResult(meta.template,{result:[{posting_number:'1',reasons:[{id:1,title:'Причина',type_id:2}]}],phone:'+79990000000',email:'x@example.test',address:'private',customer_name:'Secret'}); assert.equal(clean.result[0].reasons[0].title,'Причина'); assert.equal(clean.phone,'[REDACTED]'); assert.equal(clean.email,'[REDACTED]'); assert.equal(clean.address,'[REDACTED]'); assert.equal(clean.customer_name,'[REDACTED]'); console.log('B46_SAFE_PROJECTION_PASS');
for(const[o,p]of Object.entries({seller_action_candidates:'/v1/seller-actions/products/candidates',posting_fbo_get:'/v2/posting/fbo/get',posting_fbs_cancel_reason_list:'/v2/posting/fbs/cancel-reason/list',cancel_reason_list:'/v1/cancel-reason/list'})) assert.equal(R.OPERATIONS[o]?.path,p,o); console.log('B46_B45_AND_EARLIER_SEMANTICS_CARRY_FORWARD_PASS');
const H={'content_script.js':'a95b0be6bdd92e6a2caad82c9cbbed79df72e21991eae89affc8bb5bcad824bd','service_worker.js':'b995ad6eaf6556eac31f728a3640b77b08d6354d5e7e22f5a34f030902059f87','shared/bridge_autorun_model.js':'c248915a64ea0d9e2db014d66ab27a4bc182553cc24c5d6d0c9f43729e6e20b5','shared/work_session_model.js':'11e91d850a3d69711fefdaadb6617b825350d9382b9bc55cabdbbc9b255c9855','shared/ozon_provider.js':'16e8f85303e7a6a57d0fc76a6ea0e2e9dd8537341fa57397b38b0c0d52dda97b','shared/provider_transport_core.js':'7c346ad77dce1bbac73a2170f2f07fe6845f52a10a5b30f448afef2b80c5abb8','shared/manual_controls.js':'81f302487da7b5ff7c1b746298353438b2cfec100a5bb8f7fa2c80d1e033c81e','shared/ozon_guidance.js':'8de69833524c569bed09d5799479f2a0cd8f1844a2cf5d7d460caa3b1bb74508'};
for(const[f,h]of Object.entries(H)) assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex'),h,f); console.log('B46_PROTECTED_RUNTIME_IDENTITIES_PASS');
for(const f of ['shared/ozon_operation_registry.js','shared/ozon_contract.js']){const t=fs.readFileSync(path.join(root,f),'utf8'),i=t.indexOf(operation); assert(i>=0); assert(!/auto.?paginate|automatic pagination|retry|polling|provider chaining|secondary detail call|fanout/i.test(t.slice(Math.max(0,i-500),i+1800)));} console.log('B46_NO_HIDDEN_PAGINATION_RETRY_POLLING_FANOUT_CHAINING_PASS');
if(swaggerPath){const raw=fs.readFileSync(swaggerPath); assert.equal(raw.length,3933043); assert.equal(crypto.createHash('sha256').update(raw).digest('hex'),'39e053a147180d1df4ded6ed0272aaaf02dd6a371144d8ebed7113fd218e4b40'); const sw=JSON.parse(raw); assert.equal(sw.openapi,'3.0.0'); assert.equal(Object.keys(sw.paths).length,463); const x=sw.paths[apiPath]?.post; assert(x); assert.equal(x.operationId,'PostingAPI_GetPostingFbsCancelReasonV1'); assert.deepEqual(x.tags,['FBS']); assert.notEqual(x.deprecated,true); assert(!/устаревает|будет отключ/i.test(x.description||'')); const snap=E.compileSnapshot(sw,{source_hash:'b46-exact-swagger'}), ent=snap.operations[`POST ${apiPath}`]; assert(ent); assert.equal(ent.default_access,'ALL_ACCOUNTS'); assert.equal(ent.endpoint_allowed_subscription_types,null);
 function walk(s,p='',seen=new Set(),out=[]){if(!s||typeof s!=='object')return out;if(s.$ref){if(seen.has(s.$ref))return out;let y=sw;for(const z of s.$ref.slice(2).split('/'))y=y[z];return walk(y,p,new Set([...seen,s.$ref]),out)}for(const[k,v]of Object.entries(s.properties||{})){const q=p?`${p}.${k}`:k;out.push(q);walk(v,q,seen,out)}if(s.items)walk(s.items,p+'[]',seen,out);for(const key of ['allOf','oneOf','anyOf'])for(const z of s[key]||[])walk(z,p,seen,out);return out}
 const schema=x.responses?.['200']?.content?.['application/json']?.schema, props=walk(schema); assert(!props.some(z=>/(^|\.)(phone|email|address|customer|client|person|passport|driver|sender|recipient|buyer|file_url|file|barcode|token|webhook)(\.|$)/i.test(z)),`unsafe response property ${props.find(z=>/(phone|email|address|customer|client|person|passport|driver|sender|recipient|buyer|file_url|file|barcode|token|webhook)/i.test(z))}`); assert.deepEqual(props.sort(),['result','result[].posting_number','result[].reasons','result[].reasons[].id','result[].reasons[].title','result[].reasons[].type_id'].sort()); console.log('B46_EXACT_SWAGGER_CURRENTNESS_ENTITLEMENTS_PRIVACY_PASS');}
console.log('B46_AUTHOR_CI_GATE_PASS');
