import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import path from 'node:path';
import {pathToFileURL as U} from 'node:url';
const root=path.resolve(process.argv[2]); const swaggerPath=process.argv[3]?path.resolve(process.argv[3]):null;
const load=n=>import(U(path.join(root,'shared',n)).href+`?b48=${Date.now()}${n}`);
for(const n of ['runtime_names.js','ozon_operation_registry.js','ozon_entitlements.js','ozon_contract.js','ozon_guidance.js']) await load(n);
const R=globalThis.OzonOperationRegistry,E=globalThis.OzonEntitlements,C=globalThis.OzonContract,G=globalThis.OzonGuidance; assert(R&&E&&C&&G);
const operation='fbo_draft_timeslot_info', apiPath='/v2/draft/timeslot/info', meta=R.OPERATIONS[operation]; assert(meta);
for(const[k,v]of Object.entries({provider:'seller_api',method:'POST',path:apiPath,effect:'READ',request_style:'json_body',execution_enabled:true,currentness:'current',safety_class:'READ_SAFE',privacy_policy:'safe_projection',cluster:'supplies_fbo',section:'timeslots',guidance_visibility:'user',entitlement_key:`POST ${apiPath}`,workflow_role:'single_read'})) assert.deepEqual(meta[k],v,`${operation}.${k}`);
assert.equal(R.catalogValidation(C.OPERATIONS).ok,true); console.log('B48_FBO_DRAFT_TIMESLOT_REGISTRY_PASS');
let r=C.buildRequest(C.normalizeCommand({operation,params:{date_from:'2026-08-28',date_to:'2026-08-29',draft_id:1,supply_type:'DIRECT',selected_cluster_warehouses:[{macrolocal_cluster_id:2,storage_warehouse_id:3}]}}),{});
assert.equal(r.url,'https://api-seller.ozon.ru/v2/draft/timeslot/info'); assert.equal(r.method,'POST'); assert.deepEqual(JSON.parse(r.body),{date_from:'2026-08-28',date_to:'2026-08-29',draft_id:1,supply_type:'DIRECT',selected_cluster_warehouses:[{macrolocal_cluster_id:2,storage_warehouse_id:3}]});
// Swagger contains a malformed literal pattern " YYYY-MM-DD" (not a usable date regex), so B48 does not silently repair it or invent a semantic 28-day validator.
r=C.buildRequest(C.normalizeCommand({operation,params:{date_from:'',date_to:'schema-pattern-is-malformed',draft_id:-1,supply_type:'CROSSDOCK',selected_cluster_warehouses:[]}}),{}); assert.deepEqual(JSON.parse(r.body),{date_from:'',date_to:'schema-pattern-is-malformed',draft_id:-1,supply_type:'CROSSDOCK',selected_cluster_warehouses:[]});
r=C.buildRequest(C.normalizeCommand({operation,params:{date_from:'x',date_to:'y',draft_id:1,supply_type:'MULTI_CLUSTER',selected_cluster_warehouses:[{}]}}),{}); assert.equal(JSON.parse(r.body).selected_cluster_warehouses.length,1);
const bad=(p,c='INVALID_OPERATION_PARAMS')=>assert.throws(()=>C.normalizeCommand({operation,params:p}),e=>e?.code===c);
bad({}); bad({date_from:'a',date_to:'b',draft_id:1,supply_type:'WRONG',selected_cluster_warehouses:[]}); bad({date_from:'a',date_to:'b',draft_id:1,supply_type:'DIRECT',selected_cluster_warehouses:Array.from({length:21},()=>({}))},'OZON_LIMIT_VIOLATION'); bad({date_from:'a',date_to:'b',draft_id:1,supply_type:'DIRECT',selected_cluster_warehouses:[{macrolocal_cluster_id:'1'}]}); bad({date_from:'a',date_to:'b',draft_id:1,supply_type:'DIRECT',selected_cluster_warehouses:[],url:'https://evil.example'},'TRANSPORT_INJECTION_REJECTED'); console.log('B48_FBO_DRAFT_TIMESLOT_EXACT_REQUEST_CONTRACT_PASS');
const q=E.requirementFor(C.normalizeCommand(meta.template)),pl=C.planCommandForSellerCapability(C.normalizeCommand(meta.template),null); assert.equal(q.known,true); assert.equal(q.required,false); assert.equal(q.default_access,'ALL_ACCOUNTS'); assert.equal(pl.action,'execute'); console.log('B48_FBO_DRAFT_TIMESLOT_ENTITLEMENT_PASS');
const gd=G.result({status:'guidance',cluster:'supplies_fbo',section:'timeslots',version:2}); assert(gd.choices.some(x=>x.operation===operation)); assert.equal(gd.physical_business_request_count,0); assert.equal(gd.external_request_executed,false); console.log('B48_GUIDANCE_ZERO_REQUEST_PASS');
const clean=C.sanitizeResult(meta.template,{error_reason:'UNSPECIFIED',result:{requested_date_from:'2026-08-28',requested_date_to:'2026-08-29',drop_off_warehouse_timeslots:{current_time_in_timezone:'2026-08-28T12:00:00',warehouse_timezone:'Europe/Moscow',days:[{date_in_timezone:'2026-08-28',timeslots:[{from_in_timezone:'10:00',to_in_timezone:'12:00'}]}]}},phone:'+79990000000',email:'x@example.test',address:'private',customer_name:'Secret'}); assert.equal(clean.result.drop_off_warehouse_timeslots.warehouse_timezone,'Europe/Moscow'); assert.equal(clean.phone,'[REDACTED]'); assert.equal(clean.email,'[REDACTED]'); assert.equal(clean.address,'[REDACTED]'); assert.equal(clean.customer_name,'[REDACTED]'); console.log('B48_SAFE_PROJECTION_PASS');
for(const[o,p]of Object.entries({posting_unpaid_legal_product_list:'/v1/posting/unpaid-legal/product/list',posting_fbs_cancel_reason:'/v1/posting/fbs/cancel-reason',fbo_draft_create_info:'/v2/draft/create/info',fbo_draft_warehouse_list:'/v1/warehouse/fbo/list',supply_order_timeslot_list:'/v2/supply-order/timeslot/list'})) assert.equal(R.OPERATIONS[o]?.path,p,o); console.log('B48_B47_AND_EARLIER_SEMANTICS_CARRY_FORWARD_PASS');
const H={'content_script.js':'a95b0be6bdd92e6a2caad82c9cbbed79df72e21991eae89affc8bb5bcad824bd','service_worker.js':'b995ad6eaf6556eac31f728a3640b77b08d6354d5e7e22f5a34f030902059f87','shared/bridge_autorun_model.js':'c248915a64ea0d9e2db014d66ab27a4bc182553cc24c5d6d0c9f43729e6e20b5','shared/work_session_model.js':'11e91d850a3d69711fefdaadb6617b825350d9382b9bc55cabdbbc9b255c9855','shared/ozon_provider.js':'16e8f85303e7a6a57d0fc76a6ea0e2e9dd8537341fa57397b38b0c0d52dda97b','shared/provider_transport_core.js':'7c346ad77dce1bbac73a2170f2f07fe6845f52a10a5b30f448afef2b80c5abb8','shared/manual_controls.js':'81f302487da7b5ff7c1b746298353438b2cfec100a5bb8f7fa2c80d1e033c81e','shared/ozon_guidance.js':'8de69833524c569bed09d5799479f2a0cd8f1844a2cf5d7d460caa3b1bb74508'}; for(const[f,h]of Object.entries(H)) assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex'),h,f); console.log('B48_PROTECTED_RUNTIME_IDENTITIES_PASS');
for(const f of ['shared/ozon_operation_registry.js','shared/ozon_contract.js']){const t=fs.readFileSync(path.join(root,f),'utf8'),i=t.indexOf(operation); assert(i>=0); assert(!/auto.?paginate|automatic pagination|retry|polling|provider chaining|secondary detail call|fanout/i.test(t.slice(Math.max(0,i-600),i+2600)));} console.log('B48_NO_HIDDEN_PAGINATION_RETRY_POLLING_FANOUT_CHAINING_PASS');
if(swaggerPath){const raw=fs.readFileSync(swaggerPath); assert.equal(raw.length,3933043); assert.equal(crypto.createHash('sha256').update(raw).digest('hex'),'39e053a147180d1df4ded6ed0272aaaf02dd6a371144d8ebed7113fd218e4b40'); const sw=JSON.parse(raw); assert.equal(sw.openapi,'3.0.0'); assert.equal(Object.keys(sw.paths).length,463); const x=sw.paths[apiPath]?.post; assert.equal(x.operationId,'DraftTimeslotInfo'); assert.deepEqual(x.tags,['FboSupplyRequest']); assert.notEqual(x.deprecated,true); assert(!/устаревает|будет отключ/i.test(x.description||'')); const req=sw.components.schemas.v2DraftTimeslotInfoRequest; assert.deepEqual(req.required,['date_from','date_to','draft_id','selected_cluster_warehouses','supply_type']); assert.equal(req.properties.date_from.pattern,' YYYY-MM-DD'); assert.equal(req.properties.date_to.pattern,' YYYY-MM-DD'); assert.equal(req.properties.selected_cluster_warehouses.maxItems,20); assert.deepEqual(req.properties.supply_type.enum,['CROSSDOCK','DIRECT','MULTI_CLUSTER']); const snap=E.compileSnapshot(sw,{source_hash:'b48-exact-swagger'}).operations[`POST ${apiPath}`]; assert.equal(snap.default_access,'ALL_ACCOUNTS'); assert.equal(snap.endpoint_allowed_subscription_types,null); const old=sw.paths['/v1/supply-order/timeslot/get']?.post; assert(/19 августа 2026/.test(old?.description||'')); assert.equal(Object.values(R.OPERATIONS).some(m=>m.path==='/v1/supply-order/timeslot/get'),false); const resp=sw.components.schemas.v2DraftTimeslotInfoResponse; const seen=new Set(),props=[]; const walk=(s,p='')=>{if(!s||typeof s!=='object')return;if(s.$ref){if(seen.has(s.$ref))return;seen.add(s.$ref);let z=sw;for(const q of s.$ref.slice(2).split('/'))z=z[q];walk(z,p);return;}for(const[k,v]of Object.entries(s.properties||{})){const q=p?`${p}.${k}`:k;props.push(q);walk(v,q);}if(s.items)walk(s.items,p+'[]');for(const z of s.allOf||[])walk(z,p);}; walk(resp); assert(!props.some(z=>/(^|\.)(phone|email|address|customer|sender|driver|passport|file_url|barcode|token|webhook)(\.|$)/i.test(z)),props.join(',')); console.log('B48_EXACT_SWAGGER_CURRENTNESS_ENTITLEMENT_PRIVACY_GAP_PASS');}
console.log('B48_AUTHOR_CI_GATE_PASS');
