import assert from'node:assert/strict';import fs from'node:fs';import crypto from'node:crypto';import path from'node:path';import{pathToFileURL as u}from'node:url';
const root=path.resolve(process.argv[2]||'/tmp/ozon-b23-exact'),swp=process.argv[3]?path.resolve(process.argv[3]):null,load=n=>import(u(path.join(root,'shared',n)).href+`?b23=${Date.now()}${n}`);for(const n of['runtime_names.js','ozon_operation_registry.js','ozon_entitlements.js','ozon_contract.js','ozon_guidance.js'])await load(n);const R=globalThis.OzonOperationRegistry,E=globalThis.OzonEntitlements,C=globalThis.OzonContract,G=globalThis.OzonGuidance;
const O={seller_info:'/v1/seller/info',seller_ozon_logistics_info:'/v1/seller/ozon-logistics/info'};for(const[a,p]of Object.entries(O)){const m=R.OPERATIONS[a];for(const[k,v]of Object.entries({provider:'seller_api',method:'POST',path:p,effect:'READ',request_style:'no_body',execution_enabled:true,currentness:'current',safety_class:'READ_SAFE',privacy_policy:'safe_projection',cluster:'account_access',section:'seller_settings',workflow_role:'single_read',guidance_visibility:'user',entitlement_key:`POST ${p}`}))assert.deepEqual(m[k],v,`${a}.${k}`)}assert.equal(R.catalogValidation(C.OPERATIONS).ok,true);console.log('B23_SELLER_ACCOUNT_LOGISTICS_REGISTRY_PASS');
for(const[a,p]of Object.entries(O)){const c=C.normalizeCommand({operation:a,params:{}}),r=C.buildRequest(c,{});assert.equal(r.url,`https://api-seller.ozon.ru${p}`);assert.equal(r.method,'POST');assert.equal(r.body,undefined);assert.throws(()=>C.normalizeCommand({operation:a,params:{x:1}}),e=>e?.code==='INVALID_OPERATION_PARAMS');assert.throws(()=>C.normalizeCommand({operation:a,params:{url:'https://evil.example'}}),e=>e?.code==='TRANSPORT_INJECTION_REJECTED');const q=E.requirementFor(c),pl=C.planCommandForSellerCapability(c,null);assert.equal(q.required,false);assert.equal(pl.action,'execute');assert.equal(pl.planning.entitlement.capability_required,false)}console.log('B23_SELLER_ACCOUNT_LOGISTICS_EXACT_REQUEST_PASS');console.log('B23_SELLER_ACCOUNT_LOGISTICS_CONTRACTS_PASS');console.log('B23_SELLER_ACCOUNT_LOGISTICS_ENTITLEMENTS_PASS');
const g=G.result({status:'guidance',cluster:'account_access',section:'seller_settings',version:2});for(const a of Object.keys(O))assert(g.choices.some(x=>x.operation===a));assert.equal(g.external_request_executed,false);assert.equal(g.physical_business_request_count,0);console.log('B23_SELLER_ACCOUNT_LOGISTICS_GUIDANCE_ZERO_REQUEST_PASS');
for(const[a,p]of Object.entries({posting_fbs_cancel_reason_list:'/v2/posting/fbs/cancel-reason/list',cancel_reason_list_by_order:'/v1/cancel-reason/list-by-order',return_giveout_info:'/v1/return/giveout/info',roles:'/v1/roles',product_certificate_info:'/v1/product/certificate/info',review_comment_list:'/v1/review/comment/list',supply_order_list:'/v3/supply-order/list'}))assert.equal(R.OPERATIONS[a]?.path,p,a);console.log('B23_B22_B21_B20_B19_B18_B17_B16_B15_B14_B13_B12_B11_B10_B9_B8_B7_SEMANTICS_CARRY_FORWARD_PASS');
const H={'content_script.js':'a95b0be6bdd92e6a2caad82c9cbbed79df72e21991eae89affc8bb5bcad824bd','service_worker.js':'b995ad6eaf6556eac31f728a3640b77b08d6354d5e7e22f5a34f030902059f87','shared/bridge_autorun_model.js':'c248915a64ea0d9e2db014d66ab27a4bc182553cc24c5d6d0c9f43729e6e20b5','shared/work_session_model.js':'11e91d850a3d69711fefdaadb6617b825350d9382b9bc55cabdbbc9b255c9855','shared/ozon_provider.js':'16e8f85303e7a6a57d0fc76a6ea0e2e9dd8537341fa57397b38b0c0d52dda97b','shared/provider_transport_core.js':'7c346ad77dce1bbac73a2170f2f07fe6845f52a10a5b30f448afef2b80c5abb8','shared/manual_controls.js':'81f302487da7b5ff7c1b746298353438b2cfec100a5bb8f7fa2c80d1e033c81e','shared/ozon_guidance.js':'8de69833524c569bed09d5799479f2a0cd8f1844a2cf5d7d460caa3b1bb74508'};for(const[p,h]of Object.entries(H))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex'),h,p);console.log('B23_SELLER_ACCOUNT_LOGISTICS_PROTECTED_RUNTIME_IDENTITIES_PASS');
if(swp){const sw=JSON.parse(fs.readFileSync(swp,'utf8'));assert.equal(sw.openapi,'3.0.0');assert.equal(Object.keys(sw.paths).length,463);const I={'/v1/seller/info':'SellerAPI_SellerInfo','/v1/seller/ozon-logistics/info':'SellerAPI_SellerOzonLogisticsInfo'};for(const[p,id]of Object.entries(I)){const o=sw.paths[p].post;assert.equal(o.operationId,id);assert.notEqual(o.deprecated,true);assert((o.tags||[]).includes('SellerInfo'));assert.equal(o.requestBody,undefined)}const s=E.compileSnapshot(sw);assert.equal(s.unresolved_rule_count,12);for(const p of Object.keys(I)){const q=s.operations[`POST ${p}`];assert.equal(q.default_access,'ALL_ACCOUNTS');assert.equal(q.endpoint_allowed_subscription_types,null)}console.log('B23_SELLER_ACCOUNT_LOGISTICS_EXACT_SWAGGER_CURRENTNESS_PASS');console.log('B23_SELLER_ACCOUNT_LOGISTICS_EXACT_ENTITLEMENTS_PASS')}
let n=0;for(const p of fs.readdirSync(root,{recursive:true}))if(typeof p==='string'&&p.endsWith('.js'))n++;console.log(`B23_SYNTAX_DECLARED_JS=${n}`);
