import assert from 'node:assert/strict';
import fs from 'node:fs'; import crypto from 'node:crypto'; import path from 'node:path'; import {pathToFileURL} from 'node:url';
const root=process.argv[2]||'/tmp/ozon-b17-exact';
for(const n of ['runtime_names.js','ozon_operation_registry.js','ozon_entitlements.js','ozon_contract.js','ozon_guidance.js']) await import(pathToFileURL(path.join(root,'shared',n)).href+`?b17=${Date.now()}-${n}`);
const R=globalThis.OzonOperationRegistry,E=globalThis.OzonEntitlements,C=globalThis.OzonContract,G=globalThis.OzonGuidance; assert(R&&E&&C&&G);
const ops={review_comment_list:['/v1/review/comment/list','json_body','review_comments','PERSONAL_DATA_READ_GATED'],review_count:['/v2/review/count','no_body','reviews','READ_SAFE'],question_answer_list:['/v1/question/answer/list','json_body','answers','PERSONAL_DATA_READ_GATED'],question_count:['/v1/question/count','no_body','questions','READ_SAFE'],question_info:['/v1/question/info','json_body','questions','PERSONAL_DATA_READ_GATED'],question_top_sku:['/v1/question/top-sku','json_body','questions','READ_SAFE']};
for(const [a,[p,style,section,safety]] of Object.entries(ops)){const m=R.OPERATIONS[a]; assert(m,a); assert.equal(m.provider,'seller_api'); assert.equal(m.method,'POST'); assert.equal(m.path,p); assert.equal(m.effect,'READ'); assert.equal(m.request_style,style); assert.equal(m.execution_enabled,true); assert.equal(m.currentness,'current'); assert.equal(m.safety_class,safety); assert.equal(m.cluster,'reviews_questions'); assert.equal(m.section,section); assert.equal(m.workflow_role,'single_read'); assert.equal(m.entitlement_key,`POST ${p}`); if(safety==='PERSONAL_DATA_READ_GATED'){assert.equal(m.privacy_policy,'operator_personal_data_gate');assert.equal(m.policy_group,'personal_data_read');assert.equal(m.default_allowed,false);assert.equal(m.guidance_visibility,'conditional')}else{assert.equal(m.privacy_policy,'safe_projection');assert.equal(m.guidance_visibility,'user')}}
assert.equal(R.catalogValidation(C.OPERATIONS).ok,true);
for(const p of ['/v1/review/comment/create','/v2/review/comment/delete','/v2/review/change-status','/v1/question/answer/create','/v1/question/answer/delete','/v1/question/change-status']) assert.equal(Object.values(R.OPERATIONS).some(x=>x?.path===p&&x?.execution_enabled),false,p);
console.log('B17_REVIEWS_QUESTIONS_EXTENDED_REGISTRY_PASS');
const build=(operation,params)=>{const c=C.normalizeCommand({operation,params}); return [c,C.buildRequest(c,{})]}; const rejects=(o,p,c)=>assert.throws(()=>C.normalizeCommand({operation:o,params:p}),e=>e?.code===c);
let [c,r]=build('review_comment_list',{review_id:'R',limit:100,sort_dir:'ASC'}); assert.equal(r.url,'https://api-seller.ozon.ru/v1/review/comment/list'); assert.deepEqual(JSON.parse(r.body),c.params);
[c,r]=build('review_comment_list',{filter:{sku:1,published_from:'2026-01-01T00:00:00Z',published_to:'2026-01-02T00:00:00Z'},limit:20,offset:0,sort_dir:'DESC'}); assert.deepEqual(JSON.parse(r.body),c.params);
[c,r]=build('review_count',{}); assert.equal(r.body,undefined); assert.equal(r.url,'https://api-seller.ozon.ru/v2/review/count');
[c,r]=build('question_answer_list',{question_id:'Q',sku:1,last_id:''}); assert.deepEqual(JSON.parse(r.body),c.params);
[c,r]=build('question_count',{}); assert.equal(r.body,undefined);
[c,r]=build('question_info',{question_id:'Q'}); assert.deepEqual(JSON.parse(r.body),{question_id:'Q'});
[c,r]=build('question_top_sku',{limit:100}); assert.deepEqual(JSON.parse(r.body),{limit:100});
console.log('B17_REVIEWS_QUESTIONS_EXTENDED_EXACT_REQUEST_PASS');
for(const x of [
 ['review_comment_list',{limit:20},'INVALID_OPERATION_PARAMS'],['review_comment_list',{review_id:'R',filter:{sku:1},limit:20},'INVALID_OPERATION_PARAMS'],['review_comment_list',{review_id:'R',limit:19},'OZON_LIMIT_VIOLATION'],['review_comment_list',{review_id:'R',limit:101},'OZON_LIMIT_VIOLATION'],['review_comment_list',{filter:{sku:'1'},limit:20},'INVALID_OPERATION_PARAMS'],['review_comment_list',{review_id:'R',limit:20,url:'https://evil'},'TRANSPORT_INJECTION_REJECTED'],['review_count',{x:1},'INVALID_OPERATION_PARAMS'],['question_answer_list',{question_id:'Q'},'INVALID_OPERATION_PARAMS'],['question_answer_list',{question_id:'Q',sku:'1'},'INVALID_OPERATION_PARAMS'],['question_answer_list',{question_id:'Q',sku:1,last_id:1},'INVALID_OPERATION_PARAMS'],['question_count',{x:1},'INVALID_OPERATION_PARAMS'],['question_info',{},'INVALID_OPERATION_PARAMS'],['question_top_sku',{limit:0},'OZON_LIMIT_VIOLATION'],['question_top_sku',{limit:101},'OZON_LIMIT_VIOLATION']]) rejects(...x);
console.log('B17_REVIEWS_QUESTIONS_EXTENDED_CONTRACTS_PASS');
for(const a of ['review_comment_list','review_count']){const cmd=C.normalizeCommand(R.OPERATIONS[a].template),q=E.requirementFor(cmd),p=C.planCommandForSellerCapability(cmd,null); assert.equal(q.known,false); assert.equal(q.required,false); assert.equal(p.action,'execute'); assert.equal(p.planning.entitlement.status,'ENTITLEMENT_UNKNOWN'); assert.equal(p.planning.entitlement.capability_required,false)}
for(const a of ['question_answer_list','question_count','question_info','question_top_sku']){const cmd=C.normalizeCommand(R.OPERATIONS[a].template),q=E.requirementFor(cmd); assert.equal(q.known,true); assert.equal(q.required,true); assert.deepEqual(q.allowed_subscription_types,['PREMIUM_PLUS']); let p=C.planCommandForSellerCapability(cmd,{status:'unknown',subscription_type:'UNKNOWN',probe_performed:false}); assert.equal(p.action,'reject'); assert.equal(p.error.code,'ENTITLEMENT_UNKNOWN'); p=C.planCommandForSellerCapability(cmd,{status:'known',subscription_type:'PREMIUM_PLUS',probe_performed:true}); assert.equal(p.action,'execute'); p=C.planCommandForSellerCapability(cmd,{status:'known',subscription_type:'PREMIUM_PRO',probe_performed:true}); assert.equal(p.error.code,'SUBSCRIPTION_REQUIRED')}
assert.equal(E.BUNDLED_SNAPSHOT.unresolved_rule_count,4); for(const p of ['/v1/review/comment/list','/v2/review/count']) assert(E.BUNDLED_SNAPSHOT.unresolved_rules.some(x=>x.key===`POST ${p}`&&x.reason==='endpoint_subscription_alternative_unrepresentable'));
console.log('B17_REVIEWS_QUESTIONS_EXTENDED_ENTITLEMENTS_PASS');
for(const a of ['review_comment_list','question_answer_list','question_info']) assert.equal(R.OPERATIONS[a].default_allowed,false); for(const a of ['review_count','question_count','question_top_sku']) assert.equal(R.OPERATIONS[a].safety_class,'READ_SAFE');
console.log('B17_REVIEWS_QUESTIONS_PERSONAL_DATA_BOUNDARY_PASS');
for(const [s,aa] of Object.entries({reviews:['review_count'],review_comments:['review_comment_list'],questions:['question_count','question_info','question_top_sku'],answers:['question_answer_list']})){const g=G.result({status:'guidance',cluster:'reviews_questions',section:s,version:2}); for(const a of aa)assert(g.choices.some(x=>x.operation===a)); assert.equal(g.external_request_executed,false); assert.equal(g.physical_business_request_count,0)}
console.log('B17_REVIEWS_QUESTIONS_NO_AUTOPAGINATION_GUIDANCE_ZERO_REQUEST_PASS');
for(const [a,p] of Object.entries({seller_delivery_method_list:'/v2/delivery-method/list',description_category_tree:'/v1/description-category/tree',pricing_strategy_list:'/v1/pricing-strategy/list',ozon_actions_list:'/v1/actions',product_content_rating:'/v1/product/rating-by-sku',seller_rating_summary:'/v1/rating/summary',review_list:'/v2/review/list',question_list:'/v1/question/list',supply_order_list:'/v3/supply-order/list'})){assert.equal(R.OPERATIONS[a].path,p);assert.equal(R.OPERATIONS[a].execution_enabled,true)}
assert.deepEqual(E.subscriptionTypesFromText('доступно с [Premium](https://seller-edu.ozon.ru/seller-rating/about-rating/premium-program)'),['PREMIUM']); assert.deepEqual(E.subscriptionTypesFromText('доступно с [Premium Pro](https://seller-edu.ozon.ru/seller-rating/about-rating/podpiska-premium-pro)'),['PREMIUM_PRO']);
console.log('B17_B16_B15_B14_B13_B12_B11_B10_B9_B8_B7_SEMANTICS_CARRY_FORWARD_PASS');
const sp=process.argv[3]||''; if(sp&&fs.existsSync(sp)){const b=fs.readFileSync(sp);assert.equal(b.length,3933043);assert.equal(crypto.createHash('sha256').update(b).digest('hex'),'39e053a147180d1df4ded6ed0272aaaf02dd6a371144d8ebed7113fd218e4b40');const sw=JSON.parse(b);assert.equal(Object.keys(sw.paths).length,463);const ids={'/v1/review/comment/list':'ReviewAPI_CommentList','/v2/review/count':'ReviewCountV2','/v1/question/answer/list':'QuestionAnswer_List','/v1/question/count':'Question_Count','/v1/question/info':'Question_Info','/v1/question/top-sku':'Question_TopSku'};for(const[p,id]of Object.entries(ids)){const o=sw.paths[p].post;assert.equal(o.operationId,id);assert.notEqual(o.deprecated,true)}const cm=sw.components.schemas.v1CommentListRequest;assert.deepEqual(cm.required,['limit']);assert.equal(cm.oneOf.length,2);assert.match(cm.properties.limit.description,/20/);assert.match(cm.properties.limit.description,/100/);const ans=sw.components.schemas.v1QuestionAnswerListRequest;assert.deepEqual(ans.required,['question_id','sku']);assert.equal(ans.properties.sku.format,'int64');assert.equal(ans.properties.last_id.type,null);const top=sw.components.schemas.v1QuestionTopSkuRequest;assert.equal(top.properties.limit.minimum,1);assert.equal(top.properties.limit.maximum,100);const snap=E.compileSnapshot(sw,{sourceHash:'39e053a147180d1df4ded6ed0272aaaf02dd6a371144d8ebed7113fd218e4b40',capturedAt:'2026-08-27T00:00:00.000Z'});assert.equal(snap.unresolved_rule_count,12);for(const p of ['/v1/review/comment/list','/v2/review/count'])assert.equal(snap.operations[`POST ${p}`].default_access,'UNKNOWN');for(const p of ['/v1/question/answer/list','/v1/question/count','/v1/question/info','/v1/question/top-sku'])assert.deepEqual(snap.operations[`POST ${p}`].endpoint_allowed_subscription_types,['PREMIUM_PLUS']);const cr=sw.paths['/v1/review/comment/list'].post.responses['200'].content['application/json'].example;assert.equal(typeof cr.comments[0].text,'string');const ar=sw.paths['/v1/question/answer/list'].post.responses['200'].content['application/json'].example;assert.equal(typeof ar.answers[0].author_name,'string');assert.equal(typeof ar.answers[0].text,'string');console.log('B17_REVIEWS_QUESTIONS_EXACT_SWAGGER_CURRENTNESS_AND_PRIVACY_PASS');console.log('B17_REVIEWS_QUESTIONS_EXACT_ENTITLEMENTS_PASS')}
const H={'shared/ozon_guidance.js':'8de69833524c569bed09d5799479f2a0cd8f1844a2cf5d7d460caa3b1bb74508','content_script.js':'a95b0be6bdd92e6a2caad82c9cbbed79df72e21991eae89affc8bb5bcad824bd','service_worker.js':'b995ad6eaf6556eac31f728a3640b77b08d6354d5e7e22f5a34f030902059f87','shared/bridge_autorun_model.js':'c248915a64ea0d9e2db014d66ab27a4bc182553cc24c5d6d0c9f43729e6e20b5','shared/work_session_model.js':'11e91d850a3d69711fefdaadb6617b825350d9382b9bc55cabdbbc9b255c9855','shared/ozon_provider.js':'16e8f85303e7a6a57d0fc76a6ea0e2e9dd8537341fa57397b38b0c0d52dda97b','shared/provider_transport_core.js':'7c346ad77dce1bbac73a2170f2f07fe6845f52a10a5b30f448afef2b80c5abb8','shared/manual_controls.js':'81f302487da7b5ff7c1b746298353438b2cfec100a5bb8f7fa2c80d1e033c81e'};for(const[rel,h]of Object.entries(H))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,rel))).digest('hex'),h,rel);const w=fs.readFileSync(path.join(root,'service_worker.js'),'utf8');assert.match(w,/const ANALYTICS_MIN_INTERVAL_MS = 60_000;/);assert.match(w,/const ANALYTICS_QUOTA_LAUNCH_SAFETY_MS = 5_000;/);console.log('B17_REVIEWS_QUESTIONS_PROTECTED_RUNTIME_IDENTITIES_PASS');
