import assert from 'node:assert/strict';
import fs from 'node:fs'; import crypto from 'node:crypto'; import path from 'node:path'; import {pathToFileURL} from 'node:url';
const root=process.argv[2]||'/tmp/ozon-b18-exact';
for(const n of ['runtime_names.js','ozon_operation_registry.js','ozon_entitlements.js','ozon_contract.js','ozon_guidance.js']) await import(pathToFileURL(path.join(root,'shared',n)).href+`?b18=${Date.now()}-${n}`);
const R=globalThis.OzonOperationRegistry,E=globalThis.OzonEntitlements,C=globalThis.OzonContract,G=globalThis.OzonGuidance; assert(R&&E&&C&&G);
const ops={pricing_strategy_competitors:'/v1/pricing-strategy/competitors/list',pricing_strategy_ids_by_product_ids:'/v1/pricing-strategy/strategy-ids-by-product-ids'};
for(const [a,p] of Object.entries(ops)){const m=R.OPERATIONS[a];assert(m,a);for(const [k,v] of Object.entries({provider:'seller_api',method:'POST',path:p,effect:'READ',request_style:'json_body',execution_enabled:true,currentness:'current',safety_class:'READ_SAFE',privacy_policy:'safe_projection',cluster:'prices_promotions',section:'pricing_strategy',workflow_role:'single_read',guidance_visibility:'user',entitlement_key:`POST ${p}`}))assert.equal(m[k],v,`${a}.${k}`)}
assert.equal(R.catalogValidation(C.OPERATIONS).ok,true);for(const p of ['/v1/pricing-strategy/create','/v1/pricing-strategy/update','/v1/pricing-strategy/products/add','/v1/pricing-strategy/products/delete','/v1/pricing-strategy/status','/v1/pricing-strategy/delete'])assert.equal(Object.values(R.OPERATIONS).some(x=>x?.path===p&&x?.execution_enabled),false,p);console.log('B18_PRICING_STRATEGY_EXTENDED_REGISTRY_PASS');
const build=(operation,params)=>{const c=C.normalizeCommand({operation,params});return[c,C.buildRequest(c,{})]};const rejects=(o,p,c)=>assert.throws(()=>C.normalizeCommand({operation:o,params:p}),e=>e?.code===c);
let[c,r]=build('pricing_strategy_competitors',{page:1,limit:50});assert.equal(r.url,'https://api-seller.ozon.ru/v1/pricing-strategy/competitors/list');assert.deepEqual(JSON.parse(r.body),c.params);[c,r]=build('pricing_strategy_ids_by_product_ids',{product_id:['1','9223372036854775807']});assert.equal(r.url,'https://api-seller.ozon.ru/v1/pricing-strategy/strategy-ids-by-product-ids');assert.deepEqual(JSON.parse(r.body),c.params);console.log('B18_PRICING_STRATEGY_EXTENDED_EXACT_REQUEST_PASS');
for(const x of [['pricing_strategy_competitors',{},'INVALID_OPERATION_PARAMS'],['pricing_strategy_competitors',{page:0,limit:1},'OZON_LIMIT_VIOLATION'],['pricing_strategy_competitors',{page:1,limit:0},'OZON_LIMIT_VIOLATION'],['pricing_strategy_competitors',{page:1,limit:51},'OZON_LIMIT_VIOLATION'],['pricing_strategy_competitors',{page:'1',limit:1},'INVALID_OPERATION_PARAMS'],['pricing_strategy_competitors',{page:1,limit:1,url:'https://evil'},'TRANSPORT_INJECTION_REJECTED'],['pricing_strategy_ids_by_product_ids',{},'INVALID_OPERATION_PARAMS'],['pricing_strategy_ids_by_product_ids',{product_id:[1]},'INVALID_OPERATION_PARAMS'],['pricing_strategy_ids_by_product_ids',{product_id:['9223372036854775808']},'INVALID_OPERATION_PARAMS'],['pricing_strategy_ids_by_product_ids',{product_id:Array.from({length:51},(_,i)=>String(i+1))},'OZON_LIMIT_VIOLATION'],['pricing_strategy_ids_by_product_ids',{product_id:['1'],extra:true},'UNKNOWN_OPERATION_PARAM']])rejects(...x);build('pricing_strategy_ids_by_product_ids',{product_id:[]});console.log('B18_PRICING_STRATEGY_EXTENDED_CONTRACTS_PASS');
for(const a of Object.keys(ops)){const cmd=C.normalizeCommand(R.OPERATIONS[a].template),q=E.requirementFor(cmd),p=C.planCommandForSellerCapability(cmd,null);assert.equal(q.known,true);assert.equal(q.required,false);assert.equal(p.action,'execute');assert.equal(p.planning.entitlement.capability_required,false)}console.log('B18_PRICING_STRATEGY_EXTENDED_ENTITLEMENTS_PASS');
const g=G.result({status:'guidance',cluster:'prices_promotions',section:'pricing_strategy',version:2});for(const a of Object.keys(ops))assert(g.choices.some(x=>x.operation===a),a);assert.equal(g.external_request_executed,false);assert.equal(g.physical_business_request_count,0);console.log('B18_PRICING_STRATEGY_EXTENDED_NO_AUTOPAGINATION_GUIDANCE_ZERO_REQUEST_PASS');
for(const [a,p] of Object.entries({review_comment_list:'/v1/review/comment/list',question_info:'/v1/question/info',seller_delivery_method_list:'/v2/delivery-method/list',description_category_tree:'/v1/description-category/tree',pricing_strategy_list:'/v1/pricing-strategy/list',pricing_strategy_product_info:'/v1/pricing-strategy/product/info',ozon_actions_list:'/v1/actions',product_content_rating:'/v1/product/rating-by-sku',seller_rating_summary:'/v1/rating/summary',review_list:'/v2/review/list',question_list:'/v1/question/list',supply_order_list:'/v3/supply-order/list'})){assert.equal(R.OPERATIONS[a].path,p,a);assert.equal(R.OPERATIONS[a].execution_enabled,true,a)}let q=E.requirementFor(C.normalizeCommand(R.OPERATIONS.review_list.template));assert.equal(q.known,false);q=E.requirementFor(C.normalizeCommand(R.OPERATIONS.question_list.template));assert.deepEqual(q.allowed_subscription_types,['PREMIUM_PLUS']);assert.deepEqual(E.subscriptionTypesFromText('доступно с [Premium](https://seller-edu.ozon.ru/seller-rating/about-rating/premium-program)'),['PREMIUM']);assert.deepEqual(E.subscriptionTypesFromText('доступно с [Premium Pro](https://seller-edu.ozon.ru/seller-rating/about-rating/podpiska-premium-pro)'),['PREMIUM_PRO']);console.log('B18_B17_B16_B15_B14_B13_B12_B11_B10_B9_B8_B7_SEMANTICS_CARRY_FORWARD_PASS');
const sp=process.argv[3]||'';if(sp&&fs.existsSync(sp)){const b=fs.readFileSync(sp);assert.equal(b.length,3933043);assert.equal(crypto.createHash('sha256').update(b).digest('hex'),'39e053a147180d1df4ded6ed0272aaaf02dd6a371144d8ebed7113fd218e4b40');const sw=JSON.parse(b);assert.equal(Object.keys(sw.paths).length,463);const o1=sw.paths['/v1/pricing-strategy/competitors/list'].post,o2=sw.paths['/v1/pricing-strategy/strategy-ids-by-product-ids'].post;assert.equal(o1.operationId,'pricing_competitors');assert.equal(o2.operationId,'pricing_ids');assert.notEqual(o1.deprecated,true);assert.notEqual(o2.deprecated,true);const s1=sw.components.schemas.v1GetCompetitorsRequest,s2=sw.components.schemas.v1ItemIDsRequest;assert.deepEqual(s1.required,['page','limit']);assert.match(s1.properties.page.description,/Минимальное значение — `1`/);assert.match(s1.properties.limit.description,/от `1` до `50`/);assert.deepEqual(s2.required,['product_id']);assert.equal(s2.properties.product_id.items.type,'string');assert.equal(s2.properties.product_id.items.format,'int64');assert.match(s2.properties.product_id.description,/Максимальное количество — 50/);const snap=E.compileSnapshot(sw,{sourceHash:'39e053a147180d1df4ded6ed0272aaaf02dd6a371144d8ebed7113fd218e4b40',capturedAt:'2026-08-27T00:00:00.000Z'});assert.equal(snap.unresolved_rule_count,12);for(const p of Object.values(ops)){const rr=snap.operations[`POST ${p}`];assert.equal(rr.default_access,'ALL_ACCOUNTS');assert.equal(rr.endpoint_allowed_subscription_types,null)}console.log('B18_PRICING_STRATEGY_EXTENDED_EXACT_SWAGGER_CURRENTNESS_PASS');console.log('B18_PRICING_STRATEGY_EXTENDED_EXACT_ENTITLEMENTS_PASS')}
const protectedRuntime={'shared/ozon_guidance.js':'8de69833524c569bed09d5799479f2a0cd8f1844a2cf5d7d460caa3b1bb74508','content_script.js':'a95b0be6bdd92e6a2caad82c9cbbed79df72e21991eae89affc8bb5bcad824bd','service_worker.js':'b995ad6eaf6556eac31f728a3640b77b08d6354d5e7e22f5a34f030902059f87','shared/bridge_autorun_model.js':'c248915a64ea0d9e2db014d66ab27a4bc182553cc24c5d6d0c9f43729e6e20b5','shared/work_session_model.js':'11e91d850a3d69711fefdaadb6617b825350d9382b9bc55cabdbbc9b255c9855','shared/ozon_provider.js':'16e8f85303e7a6a57d0fc76a6ea0e2e9dd8537341fa57397b38b0c0d52dda97b','shared/provider_transport_core.js':'7c346ad77dce1bbac73a2170f2f07fe6845f52a10a5b30f448afef2b80c5abb8','shared/manual_controls.js':'81f302487da7b5ff7c1b746298353438b2cfec100a5bb8f7fa2c80d1e033c81e'};for(const[rel,sha]of Object.entries(protectedRuntime))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,rel))).digest('hex'),sha,rel);const worker=fs.readFileSync(path.join(root,'service_worker.js'),'utf8');assert.match(worker,/const ANALYTICS_MIN_INTERVAL_MS = 60_000;/);assert.match(worker,/const ANALYTICS_QUOTA_LAUNCH_SAFETY_MS = 5_000;/);console.log('B18_PRICING_STRATEGY_EXTENDED_PROTECTED_RUNTIME_IDENTITIES_PASS');
