import fs from "node:fs";
const root = process.argv[2];
if (!root) throw new Error("usage: node WORK_SESSION_REFRESH_WAKE_REGRESSION_2026-08-24.mjs <extension-root>");
const worker = fs.readFileSync(`${root}/service_worker.js`, "utf8");
const assert = (value, message) => { if (!value) throw new Error(message); };
const start = worker.indexOf('case "OZ_WORK_REFRESH"');
const end = worker.indexOf('case "OZ_WORK_START"', start);
assert(start >= 0 && end > start, "Refresh route not found");
const refresh = worker.slice(start, end);
const tabReload = refresh.indexOf("await chrome.tabs.reload(tab);");
const runtimeReload = refresh.indexOf("chrome.runtime.reload()");
assert(tabReload >= 0, "Refresh does not reload the owner tab to bootstrap a fresh manifest content runtime");
assert(runtimeReload > tabReload, "extension runtime reload must be scheduled after owner-tab reload is initiated");
assert(refresh.includes("page_reload_scheduled: true") && refresh.includes("runtime_reload_scheduled: true"), "Refresh response does not expose both recovery lifecycle stages");
assert(refresh.includes("WORK_SESSION_REFRESH_TAB_RELOAD_SCHEDULED"), "Refresh tab-reload diagnostic missing");
assert(refresh.includes("WORK_REFRESH_TAB_RELOAD_FAILED") && refresh.includes("delete recoveries[key]"), "tab-reload failure does not fail closed and clear durable recovery");
assert(worker.includes("WORK_SESSION_REFRESH_RESUMED") && worker.includes("new_runtime_generation: WORKER_SESSION_ID"), "new worker recovery resume proof missing");
console.log("WORK_SESSION_REFRESH_OWNER_TAB_BOOTSTRAP_PASS");
console.log("WORK_SESSION_REFRESH_RUNTIME_RELOAD_AFTER_TAB_RELOAD_PASS");
console.log("WORK_SESSION_REFRESH_TAB_RELOAD_FAILURE_FAIL_CLOSED_PASS");
console.log("WORK_SESSION_REFRESH_WAKE_REGRESSION_PASS");
