import fs from "node:fs";
const root = process.argv[2];
if (!root) throw new Error("usage: node WORK_SESSION_REFRESH_WAKE_REGRESSION_2026-08-24.mjs <extension-root>");
const worker = fs.readFileSync(`${root}/service_worker.js`, "utf8");
const assert = (value, message) => { if (!value) throw new Error(message); };
const start = worker.indexOf('case "OZ_WORK_REFRESH"');
const end = worker.indexOf('case "OZ_WORK_START"', start);
assert(start >= 0 && end > start, "Refresh route not found");
const refresh = worker.slice(start, end);
const tabReload = refresh.indexOf("await chrome.tabs.reload(tab);");
const runtimeReload = refresh.indexOf("chrome.runtime.reload()");
assert(tabReload >= 0, "Refresh does not reload the owner tab to bootstrap a fresh manifest content runtime");
assert(runtimeReload > tabReload, "extension runtime reload must be scheduled after owner-tab reload is initiated");
assert(refresh.includes("page_reload_scheduled: true") && refresh.includes("runtime_reload_scheduled: true"), "Refresh response does not expose both recovery lifecycle stages");
assert(refresh.includes("wake_alarm_scheduled: wakeAlarmScheduled"), "Refresh does not expose post-runtime wake fallback status");
assert(refresh.includes("persistAcrossSessions: true"), "Refresh wake alarm is not persisted across runtime reload on supported Chrome");
assert(refresh.includes("WORK_SESSION_REFRESH_TAB_RELOAD_SCHEDULED"), "Refresh tab-reload diagnostic missing");
assert(refresh.includes("WORK_REFRESH_TAB_RELOAD_FAILED") && refresh.includes("delete recoveries[key]"), "tab-reload failure does not fail closed and clear durable recovery");
assert(worker.includes('const WORK_SESSION_REFRESH_WAKE_ALARM = "ozon-work-session-refresh-wake-v1"'), "Refresh wake alarm constant missing");
assert(worker.includes("async function waitForRefreshTabIdentity") && worker.includes("WORK_REFRESH_CONTENT_RECONNECT_TIMEOUT"), "new worker does not wait for fresh content runtime after page reload");
assert(worker.includes("workSessionRecoveryResumeInFlight") && worker.includes("resumeWorkSessionRecoveriesOnce"), "recovery resume is not single-flight across startup/alarm wake races");
assert(worker.includes("name === WORK_SESSION_REFRESH_WAKE_ALARM") && worker.includes("void resumeWorkSessionRecoveries()"), "wake alarm does not resume durable work recovery");
assert(worker.includes("WORK_SESSION_REFRESH_RESUMED") && worker.includes("new_runtime_generation: WORKER_SESSION_ID"), "new worker recovery resume proof missing");
console.log("WORK_SESSION_REFRESH_OWNER_TAB_BOOTSTRAP_PASS");
console.log("WORK_SESSION_REFRESH_PERSISTENT_WAKE_FALLBACK_PASS");
console.log("WORK_SESSION_REFRESH_CONTENT_RECONNECT_WAIT_PASS");
console.log("WORK_SESSION_REFRESH_RESUME_SINGLE_FLIGHT_PASS");
console.log("WORK_SESSION_REFRESH_RUNTIME_RELOAD_AFTER_TAB_RELOAD_PASS");
console.log("WORK_SESSION_REFRESH_TAB_RELOAD_FAILURE_FAIL_CLOSED_PASS");
console.log("WORK_SESSION_REFRESH_WAKE_REGRESSION_PASS");
