TRANSITIONS={
 'NEW':{'MANUAL_INPUT','CODEX_RUNNING','IGNORED'},
 'MANUAL_INPUT':{'REVIEW','IGNORED','NEW'},
 'CODEX_RUNNING':{'REVIEW','CODEX_ERROR'},
 'CODEX_ERROR':{'CODEX_RUNNING','MANUAL_INPUT','IGNORED'},
 'REVIEW':{'EDITING','SENDING','IGNORED','CLOSED','CODEX_RUNNING'},
 'EDITING':{'REVIEW','IGNORED'},
 'SENDING':{'SENT','SEND_FAILED','SEND_UNKNOWN','ANSWERED_EXTERNALLY'},
 'SEND_FAILED':{'SENDING','REVIEW','IGNORED'},
 'SEND_UNKNOWN':{'SENT','ANSWERED_EXTERNALLY'},
 'ANSWERED_EXTERNALLY':set(),
 'SENT':set(),
 'IGNORED':set(),
 'CLOSED':set(),
}
class StaleState(Exception): pass
def allowed(old,new): return new in TRANSITIONS.get(old,set())
