TRANSITIONS={'NEW':{'MANUAL_INPUT','CODEX_RUNNING','IGNORED'},'MANUAL_INPUT':{'REVIEW','IGNORED'},'CODEX_RUNNING':{'REVIEW','CODEX_ERROR'},'CODEX_ERROR':{'CODEX_RUNNING','MANUAL_INPUT','IGNORED'},'REVIEW':{'EDITING','CODEX_RUNNING','SENDING','IGNORED'},'EDITING':{'REVIEW','IGNORED'},'SENDING':{'SENT','SEND_FAILED','SEND_UNKNOWN'},'SEND_FAILED':set(),'SEND_UNKNOWN':set(),'SENT':set(),'IGNORED':set()}
class StaleState(Exception): pass
def allowed(old,new): return new in TRANSITIONS.get(old,set())
