from pathlib import Path

ROOT = Path('tooling/llm-api-bridges/ozon-seller/dist-step7-candidate')


def replace_once(path, old, new, label):
    text = path.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected exactly one anchor, got {count}')
    path.write_text(text.replace(old, new))


content = ROOT / 'attachment_delivery_port_content.js'
replace_once(content,
'''  function request(type, payload = {}, timeoutMs = PORT_REQUEST_TIMEOUT_MS) {\n    return new Promise((resolve) => {\n      const port = ensurePort();\n      if (!port) { resolve({ ok: false, code: "ATTACHMENT_PORT_UNAVAILABLE", error: "Attachment delivery port is unavailable." }); return; }\n      const requestId = `${runtime.id}:${++runtime.request_seq}`;''',
'''  function liveOwnerBinding() {\n    const here = identity();\n    if (here.status !== "confirmed" || !here.conversation_id || !here.origin) return null;\n    return { origin: String(here.origin).toLowerCase(), conversation_id: String(here.conversation_id).toLowerCase() };\n  }\n\n  function request(type, payload = {}, timeoutMs = PORT_REQUEST_TIMEOUT_MS) {\n    return new Promise((resolve) => {\n      const port = ensurePort();\n      if (!port) { resolve({ ok: false, code: "ATTACHMENT_PORT_UNAVAILABLE", error: "Attachment delivery port is unavailable." }); return; }\n      const liveOwner = liveOwnerBinding();\n      if (!liveOwner) { resolve({ ok: false, code: "ATTACHMENT_LIVE_OWNER_UNAVAILABLE", error: "Current AI conversation identity is unavailable." }); return; }\n      const requestId = `${runtime.id}:${++runtime.request_seq}`;''', 'content request producer')
replace_once(content,
'      try { port.postMessage({ request_id: requestId, type, ...payload }); }',
'      try { port.postMessage({ request_id: requestId, type, ...payload, live_owner: liveOwner }); }', 'reserved live_owner')
replace_once(content,
'''    const response = await request("OZ_ATTACHMENT_RECOVERY_GET", { conversation_key: key });\n    return response?.ok ? response.recovery || null : null;\n  }\n\n  async function recoverCurrent() {\n    if (!current()) return { ok: false, code: "ATTACHMENT_RUNTIME_DISPOSED" };\n    const recovery = await queryRecovery();\n    if (recovery) return await processRecovery(recovery);\n    return { ok: true, recovery: null };\n  }''',
'''    const response = await request("OZ_ATTACHMENT_RECOVERY_GET", { conversation_key: key });\n    if (!response?.ok) throw Object.assign(new Error(response?.error || "Attachment recovery request failed."), { code: response?.code || "ATTACHMENT_RECOVERY_FAILED" });\n    return response.recovery || null;\n  }\n\n  async function recoverCurrent() {\n    if (!current()) return { ok: false, code: "ATTACHMENT_RUNTIME_DISPOSED" };\n    try {\n      const recovery = await queryRecovery();\n      if (recovery) return await processRecovery(recovery);\n      return { ok: true, recovery: null };\n    } catch (error) {\n      status(`Ozon: ошибка проверки доставки файла (${error?.code || "ATTACHMENT_RECOVERY_FAILED"}).`, "error");\n      return { ok: false, code: error?.code || "ATTACHMENT_RECOVERY_FAILED", error: String(error?.message || error) };\n    }\n  }''', 'recovery error visibility')

worker = ROOT / 'shared/file_delivery_port_worker.js'
replace_once(worker,
'''  function senderIdentity(sender) {\n    const rawUrl = sender?.url || sender?.tab?.url || "";\n    try {\n      const parsed = new URL(rawUrl);\n      return BB2ConversationIdentity.resolve({ origin: parsed.origin, pathname: parsed.pathname, canonicalHref: "" });\n    } catch (_) { return null; }\n  }\n\n  function assertSenderOwner(sender, owner) {\n    const senderTab = Number(sender?.tab?.id || 0);\n    if (!Number.isInteger(senderTab) || senderTab <= 0 || senderTab !== Number(owner?.tab_id || 0)) {\n      throw Object.assign(new Error("Attachment delivery request came from a non-owner tab."), { code: "ATTACHMENT_NON_OWNER_TAB" });\n    }\n    const identity = senderIdentity(sender);\n    if (!identity || identity.status !== "confirmed" || normalizeKey(identity.origin) !== normalizeKey(owner.origin) || normalizeKey(identity.conversation_id) !== normalizeKey(owner.conversation_id)) {\n      throw Object.assign(new Error("Attachment delivery request came from a different AI conversation."), { code: "ATTACHMENT_CONVERSATION_MISMATCH" });\n    }\n  }''',
'''  function senderOrigin(sender) {\n    const rawUrl = sender?.url || sender?.tab?.url || "";\n    try { return normalizeKey(new URL(rawUrl).origin); } catch (_) { return ""; }\n  }\n\n  function normalizedLiveOwner(value) {\n    if (!value || typeof value !== "object" || Array.isArray(value)) return null;\n    const origin = normalizeKey(value.origin);\n    const conversationId = normalizeKey(value.conversation_id);\n    if (!origin || !conversationId) return null;\n    try {\n      const parsed = new URL(origin);\n      if (normalizeKey(parsed.origin) !== origin || parsed.protocol !== "https:") return null;\n    } catch (_) { return null; }\n    const provider = BB2ConversationIdentity.providerForOrigin(origin);\n    if (!provider) return null;\n    const syntheticPath = provider === "alice" ? `/chat/${conversationId}` : `/c/${conversationId}`;\n    if (BB2ConversationIdentity.conversationIdFromPath(syntheticPath, provider) !== conversationId) return null;\n    return { origin, conversation_id: conversationId };\n  }\n\n  function assertSenderOwner(sender, owner, liveOwnerValue) {\n    const senderTab = Number(sender?.tab?.id || 0);\n    if (!Number.isInteger(senderTab) || senderTab <= 0 || senderTab !== Number(owner?.tab_id || 0)) {\n      throw Object.assign(new Error("Attachment delivery request came from a non-owner tab."), { code: "ATTACHMENT_NON_OWNER_TAB" });\n    }\n    const expectedOrigin = normalizeKey(owner?.origin);\n    if (!expectedOrigin || senderOrigin(sender) !== expectedOrigin) {\n      throw Object.assign(new Error("Attachment delivery request came from a different AI origin."), { code: "ATTACHMENT_ORIGIN_MISMATCH" });\n    }\n    const liveOwner = normalizedLiveOwner(liveOwnerValue);\n    if (!liveOwner) {\n      throw Object.assign(new Error("Attachment delivery request is missing a confirmed live conversation owner."), { code: "ATTACHMENT_LIVE_OWNER_REQUIRED" });\n    }\n    if (liveOwner.origin !== expectedOrigin || liveOwner.conversation_id !== normalizeKey(owner?.conversation_id)) {\n      throw Object.assign(new Error("Attachment delivery request came from a different live AI conversation."), { code: "ATTACHMENT_CONVERSATION_MISMATCH" });\n    }\n  }''', 'worker owner validator')
text = worker.read_text()
if text.count('assertSenderOwner(sender, found.owner);') != 2:
    raise SystemExit('worker owner call count mismatch')
worker.write_text(text.replace('assertSenderOwner(sender, found.owner);', 'assertSenderOwner(sender, found.owner, message.live_owner);'))
