import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const root=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:false});
const rows=[],fd=fs.openSync(path.join(out,'results.jsonl'),'wx');
const ctx=vm.createContext({URL,URLSearchParams,TextEncoder,console});
for(const name of ['wb_operations','wb_contract','wb_command_protocol'])vm.runInContext(fs.readFileSync(path.join(root,'shared',name+'.js'),'utf8'),ctx);
const P=ctx.WBCommandProtocol,C=ctx.WBContract,clone=v=>JSON.parse(JSON.stringify(v));
const api=(operation='seller_info',params={})=>'WB_API_V1\n'+JSON.stringify({operation,params});
const help=(operation='catalog',params={})=>'WB_HELP_V1\n'+JSON.stringify({operation,params});
function test(id,fn){try{const detail=fn();rows.push({id,status:'PASS',detail:detail??null})}catch(e){rows.push({id,status:'FAIL',error:e.stack})}const row=rows.at(-1);fs.writeSync(fd,JSON.stringify(row)+'\n');fs.fsyncSync(fd);console.log(row.status,id)}
const reject=(s,code)=>assert.throws(()=>P.parse(s),e=>e.code===code);
test('TA-001-SINGLE-EXACT',()=>{const p=P.parse(api());assert.equal(p.entries.length,1);assert.equal(p.fingerprint,C.commandFingerprint(C.parseCommand(api())));assert.equal(p.entries[0].command_text,api());});
test('TA-002-ORDER',()=>assert.deepEqual(clone(P.parse(api()+'\n'+api('tariff_commission')).entries.map(e=>e.operation)),['seller_info','tariff_commission']));
test('TA-007-FENCES-AND-PROSE',()=>assert.equal(P.parse('Пример\n```text\n'+api()+'\n```\nЕщё\n```\n'+api('tariff_commission')+'\n```').entries.length,2));
test('TA-008-MIXED-ORDER',()=>assert.deepEqual(clone(P.parse(help()+'\n'+api()+'\n'+help('describe',{alias:'cards_list'})).entries.map(e=>e.kind)),['help','api','help']));
test('TA-003-MALFORMED-LATER-ATOMIC',()=>reject(api()+'\nWB_API_V1 {"operation":','INVALID_JSON'));
test('UNBALANCED-QUOTED-JSON',()=>reject('WB_API_V1 {"operation":"seller_info","params":{"x":"}}','INVALID_JSON'));
for(const field of ['args','url','method','headers','authorization','token','path','query','body','constructor'])test('TA-004-TOP:'+field,()=>reject('WB_API_V1\n'+JSON.stringify({operation:'seller_info',params:{},[field]:'do-not-leak'}),'UNKNOWN_COMMAND_FIELD'));
for(const field of ['url','headers','Authorization','api-key','api_key','client_secret','access_token','__proto__'])test('TA-006-NESTED:'+field,()=>reject('WB_API_V1 '+JSON.stringify({operation:'unknown_alias',params:JSON.parse('{"'+field+'":"DO-NOT-LEAK"}')}),'TRANSPORT_INJECTION_REJECTED'));
test('REQUIRES-PARAMS',()=>reject('WB_API_V1 {"operation":"seller_info"}','INVALID_OPERATION_PARAMS'));
test('ARRAY-PARAMS-REJECT',()=>reject('WB_API_V1 {"operation":"seller_info","params":[]}','INVALID_OPERATION_PARAMS'));
test('TA-009-DISABLED-LOCAL',()=>{const e=P.parse(api('subscriptions')).entries[0];assert.equal(e.code,'OPERATION_BLOCKED');assert.equal(e.command,null)});
test('TA-010-UNKNOWN-LOCAL',()=>assert.equal(P.parse(api('unknown_alias')).entries[0].code,'UNSUPPORTED_OPERATION'));
test('MARKER-IN-STRING-NOT-COMMAND',()=>{const literal='} { \\ " WB_HELP_V1 {"operation":"catalog","params":{}}';const e=P.parse(api('cards_list',{settings:{textSearch:literal}})+'\n'+api());assert.equal(e.entries.length,2);assert.equal(e.entries[0].command.body.settings.textSearch,literal)});
test('NBSP-IN-PAYLOAD-PRESERVED',()=>assert.equal(P.parse(api('cards_list',{settings:{textSearch:'A\u00a0B'}})).entries[0].command.body.settings.textSearch,'A\u00a0B'));
test('TOKEN-BOUNDARIES',()=>{assert.equal(P.hasCommands('xWB_API_V1 {} WB_API_V10 {} WB_API_V1_suffix {}'),false);reject('WB_API_V10 {}','NO_COMMAND_ENVELOPES')});
test('MARKER-MISSING-OBJECT',()=>reject('WB_API_V1\n[]','MISSING_JSON'));
test('BOUND-MAX-COMMANDS',()=>{assert.equal(P.parse(Array(32).fill(api()).join('\n')).entries.length,32);reject(Array(33).fill(api()).join('\n'),'TOO_MANY_COMMANDS')});
test('BOUND-MAX-SOURCE',()=>reject('x'.repeat(P.MAX_SOURCE_CHARS+1),'COMMAND_SOURCE_TOO_LARGE'));
test('TA-013-DEPENDENCY-NOT-INTERPOLATED',()=>{const alias=Object.keys(C.OPERATIONS).find(a=>C.OPERATIONS[a].execution_enabled&&C.OPERATIONS[a].path.includes('{'));const m=C.OPERATIONS[alias],key=m.path.match(/\{(.*?)\}/)[1];reject(api()+ '\n'+api(alias,{path:{[key]:'$prev.id'}}),'INVALID_PATH_PARAM')});
test('TA-029-GUIDANCE-REGISTRY-COUNTS',()=>{const g=P.guidance(P.parse(help()).entries[0].command);assert.deepEqual([g.registry_total,g.registry_enabled,g.registry_disabled,g.physical_request_count],[188,172,16,0]);assert.equal(g.operations.length,25);assert.equal(g.next_offset,25)});
test('HELP-PAGING-NO-OMISSIONS',()=>{let aliases=[];for(let offset=0;offset<188;offset+=50)aliases.push(...P.guidance({operation:'catalog',params:{offset,limit:50}}).operations.map(o=>o.operation));assert.equal(new Set(aliases).size,188);assert.deepEqual(aliases,Object.keys(C.OPERATIONS).sort())});
test('HELP-DISABLED-NONRUNNABLE',()=>{const g=P.guidance({operation:'describe',params:{alias:'subscriptions'}}).operation_card;assert.equal(g.execution_enabled,false);assert.equal(g.template,null);assert.equal(g.account_access,'UNVERIFIED_REAL_ACCOUNT')});
test('HELP-BODY-REQUIRED-NO-FAKE-TEMPLATE',()=>assert.equal(P.card('cards_list').template,null));
test('HELP-VALID-ZERO-PARAM-TEMPLATE',()=>assert.deepEqual(clone(P.card('seller_info').template),{operation:'seller_info',params:{}}));
test('HELP-FAMILY-FILTER',()=>{const g=P.guidance({operation:'catalog',params:{family:'content',limit:50}});assert.ok(g.operations.length>0);assert.ok(g.operations.every(x=>x.family==='content'))});
test('HELP-BOUNDS-STRICT',()=>reject(help('catalog',{limit:1000}),'HELP_INVALID_PAGE'));
test('HELP-UNKNOWN-FAMILY',()=>reject(help('catalog',{family:'not_wb'}),'HELP_UNKNOWN_FAMILY'));
test('HELP-UNKNOWN-OPERATION',()=>reject(help('send'),'HELP_UNSUPPORTED_OPERATION'));
test('HELP-UNKNOWN-PARAM',()=>reject(help('catalog',{random:'x'}),'HELP_UNKNOWN_PARAM'));
test('UNKNOWN-ERROR-NO-RAW-CONTENT',()=>{try{P.parse('WB_API_V1 {"secret":"do-not-leak"}')}catch(e){assert.equal(e.message.includes('do-not-leak'),false)}});
test('PLAN-IMMUTABLE',()=>{const p=P.parse(api());assert.ok(Object.isFrozen(p));assert.ok(Object.isFrozen(p.entries[0].command))});
const hashes=Object.fromEntries(['wb_operations','wb_contract','wb_command_protocol'].map(n=>[n,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'shared',n+'.js'))).digest('hex')]));
const summary={scope:'Shared protocol/guidance only; not worker/browser acceptance',checks:rows.length,passed:rows.filter(r=>r.status==='PASS').length,failed:rows.filter(r=>r.status==='FAIL').length,real_wb_requests:0,hashes};fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify(summary,null,2)+'\n');fs.closeSync(fd);console.log(JSON.stringify(summary));if(summary.failed)process.exitCode=1;
