// Run: node INITIAL_ERROR_REGRESSION.mjs /path/to/extracted/wb /new/evidence/directory
// Exact WB worker/importScripts; Chrome and fetch mocked; no real marketplace calls.
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
const root=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);
fs.mkdirSync(out,{recursive:false});const fd=fs.openSync(path.join(out,'results.jsonl'),'wx'),rows=[];
const identity={origin:'https://chatgpt.com',ai_id:'chatgpt',conversation_id:'11111111-1111-1111-1111-111111111111',status:'confirmed',source:'synthetic-fixture'};
const key=identity.origin+'|'+identity.conversation_id;
const api=(operation='seller_info',params={})=>'WB_API_V1\n'+JSON.stringify({operation,params});
const help=(operation='catalog',params={})=>'WB_HELP_V1\n'+JSON.stringify({operation,params});
function boot(data={}){
 let listener;const count={calls:0},tab={id:1,url:'https://chatgpt.com/c/'+identity.conversation_id};
 const binding={...identity,binding_id:'fixture-binding',revision:1,conversation_key:key};
 data={wbmb_seller_token:'offline-fixture-token',wbmb_auto_send:true,wbmb_conversation_bindings:{[key]:binding},wbmb_manual_modes:{[key]:true},wbmb_auto_runs:{},['wb_work_session_v1:'+key]:{state:'active_visible',conversation_key:key,revision:2,tab_id:1,...identity},...data};
 const sandbox={URL,URLSearchParams,TextEncoder,TextDecoder,AbortController,Headers,Response,Uint8Array,crypto:crypto.webcrypto,setTimeout,clearTimeout,console,btoa:s=>Buffer.from(s,'binary').toString('base64')};
 sandbox.chrome={runtime:{lastError:null,getURL:p=>'chrome-extension://fixture/'+p,onMessage:{addListener:f=>listener=f}},storage:{local:{async get(keys){if(keys===null)return structuredClone(data);return Object.fromEntries((Array.isArray(keys)?keys:[keys]).map(k=>[k,structuredClone(data[k])]))},async set(v){Object.assign(data,structuredClone(v))},async remove(ks){for(const k of Array.isArray(ks)?ks:[ks])delete data[k]}}},tabs:{async get(){return tab},async query(){return [tab]},sendMessage(id,m,cb){queueMicrotask(()=>cb(m.type==='WB_GET_IDENTITY'?{ok:true,identity}:{ok:false,code:'SYNTHETIC_UI_UNAVAILABLE'}))}}};
 sandbox.fetch=async()=>{count.calls++;return new Response('{"fixture":"provider success"}',{status:200,headers:{'Content-Type':'application/json'}})};
 const context=vm.createContext(sandbox);sandbox.importScripts=(...files)=>{for(const f of files)vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),context,{filename:f,timeout:3000})};
 vm.runInContext(fs.readFileSync(path.join(root,'service_worker.js'),'utf8'),context,{filename:'service_worker.js',timeout:3000});
 return {context,count,data,send(text){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('HARNESS_TIMEOUT')),5000);listener({type:'WB_EXECUTE_COMMAND',conversation_key:key,manual_request_id:'fresh-attempt',command_text:text},{tab,frameId:0,url:tab.url},r=>{clearTimeout(timer);resolve(r)})})}};
}
function local(w,r,code){assert.equal(typeof r.report_text,'string','Structured chat report missing');assert.ok(r.report_text.startsWith('WB_RESULT_V1\n'));const p=JSON.parse(r.report_text.slice(13));assert.equal(r.ok,false);assert.equal(r.bridge_error,true);assert.equal(r.pre_execution_error,true);assert.equal(p.bridge_error,true);assert.equal(p.pre_execution_error,true);assert.equal(p.http_status,0);assert.equal(p.request_meta.physical_request_count,0);assert.equal(p.request_meta.external_request_executed,false);assert.equal(p.request_meta.automatic_retry,false);assert.equal(w.count.calls,0);assert.ok(p.batch.items.some(i=>i.code===code));const op=w.data.wbmb_manual_operations?.[key];assert.equal(op?.status,'delivering');assert.equal(op.delivery_confirmed,false);assert.equal(op.outgoing_text,r.outgoing_text||r.report_text);assert.equal(op.tab_id,1);assert.equal(op.conversation_key,key);assert.ok(op.command_batch?.sha256);assert.equal(JSON.stringify(r).includes('offline-fixture-token'),false);return {code,provider_calls:0,durable_report:true};}
async function test(id,fn){let row;try{row={id,status:'PASS',detail:await fn()}}catch(e){row={id,status:'FAIL',error:e.message,stack:e.stack}}rows.push(row);fs.writeSync(fd,JSON.stringify(row)+'\n');fs.fsyncSync(fd);console.log(id,row.status,row.error||'');}
for(const [id,text,code] of [['unknown',api('definitely_unknown_operation'),'UNSUPPORTED_OPERATION'],['disabled',api('subscriptions'),'OPERATION_BLOCKED'],['malformed','WB_API_V1 {','INVALID_JSON'],['missing-json','WB_API_V1','MISSING_JSON'],['extra-field','WB_API_V1 {"operation":"seller_info","params":{},"headers":{"Authorization":"PRIVATE-SECRET"}}','UNKNOWN_COMMAND_FIELD'],['injection',api('seller_info',{url:'https://example.invalid/PRIVATE-SECRET'}),'TRANSPORT_INJECTION_REJECTED'],['invalid-help',help('unknown_help'),'HELP_UNSUPPORTED_OPERATION'],['mixed-help-api',help()+'\n'+api(),'MIXED_HELP_AND_API'],['mixed-api-help',api()+'\n'+help(),'MIXED_HELP_AND_API'],['mixed-malformed-help',api()+'\nWB_HELP_V1 {','MIXED_HELP_AND_API'],['atomic-invalid-later',api()+'\nWB_API_V1 {','INVALID_JSON']])await test(id,async()=>{const w=boot(),r=await w.send(text);const detail=local(w,r,code);assert.equal(JSON.stringify(r).includes('PRIVATE-SECRET'),false);return detail});
for(const state of ['inactive','active_hidden','recovering'])await test('work-'+state,async()=>{const w=boot({['wb_work_session_v1:'+key]:{state,conversation_key:key}});return local(w,await w.send(help()),'WORK_SESSION_NOT_VISIBLE')});
await test('competing-auto',async()=>{const w=boot({wbmb_auto_runs:{[key]:{run_id:'competing-run',conversation_key:key,status:'requesting'}}});return local(w,await w.send(api()),'AUTO_MODE_ACTIVE')});
await test('personal-off',async()=>{const w=boot();vm.runInContext(`WBRuntimePolicy={...WBRuntimePolicy,admission(){throw Object.assign(new Error('Personal data disabled'),{code:'PERSONAL_DATA_DISABLED'})}}`,w.context);return local(w,await w.send(api()),'PERSONAL_DATA_DISABLED')});
await test('quota-wait',async()=>{const w=boot();await vm.runInContext(`(async()=>{const o=await wbOwner(${JSON.stringify(key)});await WBPolicyEngine.observeRetryAfter(o.account_scope,'common','60')})()`,w.context);return local(w,await w.send(api()),'QUOTA_WAIT_NEW_EXPLICIT_COMMAND_REQUIRED')});
await test('help-no-token',async()=>{const w=boot({wbmb_seller_token:''}),r=await w.send(help());assert.equal(r.ok,true);assert.equal(w.count.calls,0);return {calls:0}});
await test('one-explicit-api',async()=>{const w=boot(),r=await w.send(api());assert.equal(r.ok,true);assert.equal(w.count.calls,1);return {mocked_calls:1}});
const summary={passed:rows.filter(r=>r.status==='PASS').length,failed:rows.filter(r=>r.status==='FAIL').length,real_provider_calls:0,scope:'synthetic exact worker; not installed chat delivery',worker_sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'service_worker.js'))).digest('hex')};fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify(summary,null,2));fs.closeSync(fd);process.exitCode=summary.failed?1:0;
