from abc import ABC,abstractmethod
class MarketplaceAdapter(ABC):
 @abstractmethod
 async def fetch_unanswered_questions(self): ...
 @abstractmethod
 async def send_answer(self,question,text): ...
 @abstractmethod
 async def reconcile_answer(self,question,expected_text,send_started_at): ...
