import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { webcrypto, createHash } from 'node:crypto';

const EXPECTED_WORKER='dfc101f6d1840af89b7dc48b6082f43b26c8143ed96086bc19ab0dfd36c21fac';
const EXPECTED_CONTENT='ab3408a2637153fa324f0b679ac5452b9b7ae0182f5ccf4f0397ccd960857dda';
const candidateDir=path.resolve(process.argv[2]||'');
if(!candidateDir||!fs.existsSync(path.join(candidateDir,'service_worker.js')))throw new Error('usage: node B06_WORKER_QUOTA_CURRENT.mjs <exact-current-candidate-dir>');
const sha=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const assert=(v,m)=>{if(!v)throw new Error(m)};
assert(sha(path.join(candidateDir,'service_worker.js'))===EXPECTED_WORKER,'worker SHA mismatch');
assert(sha(path.join(candidateDir,'content_script.js'))===EXPECTED_CONTENT,'content SHA mismatch');

const local=new Map(),session=new Map();const runtimeListeners=[],alarmListeners=[],startupListeners=[],removedListeners=[];const tabIdentities=new Map();const alarms=[];let providerCalls=[];let fetchMode='success';
function clone(v){return v===undefined?undefined:structuredClone(v)}
function get(map,keys){const out={};if(keys==null){for(const[k,v]of map)out[k]=clone(v);return Promise.resolve(out)}if(typeof keys==='string')keys=[keys];if(Array.isArray(keys)){for(const k of keys)if(map.has(k))out[k]=clone(map.get(k));}else if(typeof keys==='object'){for(const[k,d]of Object.entries(keys))out[k]=map.has(k)?clone(map.get(k)):clone(d)}return Promise.resolve(out)}
function set(map,vals){for(const[k,v]of Object.entries(vals||{}))map.set(k,clone(v));return Promise.resolve()}
function remove(map,keys){if(!Array.isArray(keys))keys=[keys];for(const k of keys)map.delete(k);return Promise.resolve()}
const chrome={runtime:{id:'b06-current',lastError:null,onMessage:{addListener(fn){runtimeListeners.push(fn)}},onStartup:{addListener(fn){startupListeners.push(fn)}},onInstalled:{addListener(){}}},storage:{local:{get:k=>get(local,k),set:v=>set(local,v),remove:k=>remove(local,k),clear:async()=>local.clear()},session:{get:k=>get(session,k),set:v=>set(session,v),remove:k=>remove(session,k),clear:async()=>session.clear()}},tabs:{get:async id=>({id,url:(tabIdentities.get(id)?.origin||'https://chatgpt.com')+'/'}),query:async()=>[],sendMessage(id,msg,cb){const response=msg?.type==='OZ_GET_IDENTITY'?{ok:true,identity:clone(tabIdentities.get(id))}:{ok:false,code:'COMPOSER_NOT_FOUND'};if(typeof cb==='function')queueMicrotask(()=>cb(response));else return Promise.resolve(response)},onRemoved:{addListener(fn){removedListeners.push(fn)}}},alarms:{create(name,info){alarms.push({name,info:clone(info)})},clear:async()=>true,get:async()=>null,getAll:async()=>[],onAlarm:{addListener(fn){alarmListeners.push(fn)}}}};
async function fakeFetch(input,init={}){const url=typeof input==='string'?input:String(input?.url||input);if(!/api-seller\.ozon\.ru/i.test(url))throw new Error(`unexpected network: ${url}`);providerCalls.push({url,at:Date.now(),mode:fetchMode});if(fetchMode==='429'){return new Response(JSON.stringify({code:8,message:'rate limit'}),{status:429,headers:{'content-type':'application/json','retry-after':'120'}})}let metricsCount=1;try{const body=JSON.parse(String(init?.body||'{}'));if(Array.isArray(body.metrics)&&body.metrics.length)metricsCount=body.metrics.length}catch(_){}const metrics=Array.from({length:metricsCount},(_,i)=>100+i);return new Response(JSON.stringify({result:{data:[{dimensions:[{id:'2026-08-17',name:'2026-08-17'}],metrics}],totals:metrics}}),{status:200,headers:{'content-type':'application/json'}})}
const sandbox={console,chrome,crypto:webcrypto,TextEncoder,TextDecoder,URL,URLSearchParams,setTimeout,clearTimeout,setInterval,clearInterval,queueMicrotask,structuredClone,fetch:fakeFetch,AbortController,Headers,Response,Request,FormData,Blob};sandbox.globalThis=sandbox;sandbox.self=sandbox;
const context=vm.createContext(sandbox);sandbox.importScripts=(...names)=>{for(const name of names){const p=path.join(candidateDir,name);vm.runInContext(fs.readFileSync(p,'utf8'),context,{filename:p})}};vm.runInContext(fs.readFileSync(path.join(candidateDir,'service_worker.js'),'utf8'),context,{filename:'service_worker.js'});assert(runtimeListeners.length===1,'runtime message listener missing');
const KEYS=context.OzonRuntime.STORAGE_KEYS,C=context.OzonContract;assert(typeof context.acquireAnalyticsProviderQuota==='function'&&typeof context.sellerQuotaIdentity==='function','quota helpers missing');
async function send(message,sender){return await new Promise((resolve,reject)=>{let done=false;const timer=setTimeout(()=>{if(!done){done=true;reject(new Error(`runtime timeout: ${message.type}`))}},5000);const ret=runtimeListeners[0](message,sender,response=>{if(done)return;done=true;clearTimeout(timer);resolve(response)});if(ret!==true&&!done){done=true;clearTimeout(timer);resolve(undefined)}})}
async function waitFor(fn,timeout=10000,step=25){const start=Date.now();while(Date.now()-start<timeout){const v=await fn();if(v)return v;await new Promise(r=>setTimeout(r,step))}throw new Error('waitFor timeout')}
function identity(origin,id){return{origin,ai_id:origin.includes('alice')?'alice':'chatgpt',conversation_id:id,status:'confirmed',source:'path',chat_path:`/${origin.includes('alice')?'chat':'c'}/${id}`}}
function binding(origin,id){const key=`${origin}|${id}`;return{key,record:{binding_id:`bind-${id}`,revision:1,origin,ai_id:origin.includes('alice')?'alice':'chatgpt',conversation_id:id,conversation_key:key,bound_at:new Date().toISOString(),updated_at:new Date().toISOString()}}}
async function addOwner(tab,id,origin='https://chatgpt.com'){const b=binding(origin,id);tabIdentities.set(tab,identity(origin,id));const bindings=(await get(local,KEYS.CONVERSATION_BINDINGS))[KEYS.CONVERSATION_BINDINGS]||{};const modes=(await get(local,KEYS.MANUAL_MODES))[KEYS.MANUAL_MODES]||{};await set(local,{[KEYS.CONVERSATION_BINDINGS]:{...bindings,[b.key]:b.record},[KEYS.MANUAL_MODES]:{...modes,[b.key]:true}});return b.key}
async function setSeller(clientId,apiKey){await set(local,{[KEYS.SELLER_CLIENT_ID]:clientId,[KEYS.SELLER_API_KEY]:apiKey,[KEYS.AUTO_SEND]:true})}
const analytics=(date,metrics=['revenue'])=>`OZON_API_V1\n${JSON.stringify({operation:'analytics_data',params:{date_from:date,date_to:date,dimension:['day'],metrics,limit:1}})}`;

local.clear();session.clear();providerCalls=[];fetchMode='success';
const sellerClient='QUOTA-SELLER-A',sellerKey1='QUOTA-KEY-A1',sellerKey2='QUOTA-KEY-A2';await setSeller(sellerClient,sellerKey1);
const key1=await addOwner(1,'11111111-1111-4111-8111-111111111111');
let accepted=await send({type:'OZ_EXECUTE_COMMAND',command_text:analytics('2026-08-17'),conversation_key:key1,manual_request_id:'first-cold'},{tab:{id:1}});assert(accepted?.ok===true&&accepted?.accepted===true,'first cold-cache request not admitted');await waitFor(()=>providerCalls.length===1,8000);const firstAt=providerCalls[0].at;
console.log('B06_FIRST_COLD_REQUEST_EXECUTED_PASS');

const idA1=await context.sellerQuotaIdentity({clientId:sellerClient,apiKey:sellerKey1});const idA2=await context.sellerQuotaIdentity({clientId:sellerClient,apiKey:sellerKey2});assert(idA1.account_hash===idA2.account_hash,'same Client-Id key rotation changed quota account');assert(idA1.credential_revision!==idA2.credential_revision,'Api-Key rotation did not change credential revision');await setSeller(sellerClient,sellerKey2);
const key2=await addOwner(2,'22222222-2222-4222-8222-222222222222','https://alice.yandex.ru');accepted=await send({type:'OZ_EXECUTE_COMMAND',command_text:analytics('2026-08-18'),conversation_key:key2,manual_request_id:'second-cold'},{tab:{id:2}});assert(accepted?.ok===true&&accepted?.accepted===true,'second same-Seller cold-cache request not admitted');const waiting=await waitFor(async()=>{const ops=(await get(local,KEYS.MANUAL_OPERATIONS))[KEYS.MANUAL_OPERATIONS]||{};const op=ops[key2];return op?.batch?.request_state==='quota_waiting'?op:null},5000);assert(providerCalls.length===1,'second same-Seller request bypassed quota');const persistedDue=Number(waiting.batch.quota_wait?.next_allowed_at||0);assert(persistedDue>=firstAt+65000-10,'same-Seller persisted due shorter than 65s guard');assert(waiting.batch.quota_wait?.family==='seller.analytics_data.v1'&&waiting.batch.quota_wait?.min_interval_ms===60000&&waiting.batch.quota_wait?.bridge_launch_safety_ms===5000&&waiting.batch.quota_wait?.effective_interval_ms===65000,'quota metadata mismatch');
console.log('B06_SECOND_COLD_REQUEST_WAITS_PASS');console.log('B06_SAME_SELLER_CHATGPT_ALICE_SHARED_BUCKET_PASS');console.log('B06_KEY_ROTATION_SAME_ACCOUNT_PASS');

const publicState=await send({type:'OZ_GET_MANUAL_STATE',conversation_key:key2},{tab:{id:2}});const publicJson=JSON.stringify(publicState);assert(publicState?.manual_operation?.quota_wait?.next_allowed_at===persistedDue,'public quota state lost due');for(const secret of [sellerClient,sellerKey1,sellerKey2,idA1.account_hash,idA2.credential_revision])assert(!publicJson.includes(secret),'public quota state leaked private account/credential data');console.log('B06_PUBLIC_QUOTA_STATE_PRIVACY_PASS');

const otherPermit=await context.acquireAnalyticsProviderQuota({clientId:'QUOTA-SELLER-B',apiKey:'QUOTA-KEY-B'});assert(otherPermit.allowed===true,'different Seller was blocked by Seller A bucket');console.log('B06_DIFFERENT_SELLER_BUCKET_INDEPENDENT_PASS');

const waitMs=Math.max(0,persistedDue-Date.now()+250);await new Promise(r=>setTimeout(r,waitMs));for(const fn of alarmListeners)await fn({name:'ozon-provider-quota-wake-v1',scheduledTime:Date.now()});await waitFor(()=>providerCalls.length===2,10000);assert(providerCalls[1].at>=persistedDue-5,'second provider call started before persisted due');await new Promise(r=>setTimeout(r,300));assert(providerCalls.length===2,'quota due created duplicate provider call');console.log('B06_DUE_AUTO_RESUME_ONE_PROVIDER_CALL_PASS');

const beforeStartup=providerCalls.length;for(const fn of startupListeners)await fn();try{await vm.runInContext('typeof resumeProviderQuotaWaits==="function"?resumeProviderQuotaWaits():Promise.resolve()',context)}catch(_){}await new Promise(r=>setTimeout(r,300));assert(providerCalls.length===beforeStartup,'startup replayed already-attempted work');console.log('B06_STARTUP_NO_REPLAY_PASS');

local.clear();session.clear();providerCalls=[];fetchMode='success';const concurrentCreds={clientId:'CONCURRENT-SELLER',apiKey:'CONCURRENT-KEY'};const [permit1,permit2]=await Promise.all([context.acquireAnalyticsProviderQuota(concurrentCreds),context.acquireAnalyticsProviderQuota(concurrentCreds)]);assert([permit1.allowed,permit2.allowed].filter(Boolean).length===1,'concurrent quota acquisition granted more than one permit');console.log('B06_CONCURRENT_ACQUIRE_ONE_PERMIT_PASS');

local.clear();session.clear();providerCalls=[];fetchMode='success';await setSeller('COALESCE-SELLER','COALESCE-KEY');const key3=await addOwner(3,'33333333-3333-4333-8333-333333333333');accepted=await send({type:'OZ_EXECUTE_COMMAND',command_text:`${analytics('2026-08-17',['revenue'])}\n\n${analytics('2026-08-17',['ordered_units'])}`,conversation_key:key3,manual_request_id:'coalesced-one-permit'},{tab:{id:3}});assert(accepted?.ok===true&&accepted?.accepted===true,'coalesced quota batch not admitted');await waitFor(()=>providerCalls.length===1,8000);await new Promise(r=>setTimeout(r,250));assert(providerCalls.length===1,'coalesced logical group consumed more than one provider call/permit');console.log('B06_COALESCED_ONE_PHYSICAL_PERMIT_PASS');

local.clear();session.clear();providerCalls=[];fetchMode='429';await setSeller('RETRY-SELLER','RETRY-KEY');const key4=await addOwner(4,'44444444-4444-4444-8444-444444444444');accepted=await send({type:'OZ_EXECUTE_COMMAND',command_text:analytics('2026-08-17'),conversation_key:key4,manual_request_id:'one-429'},{tab:{id:4}});assert(accepted?.ok===true&&accepted?.accepted===true,'429 request not admitted');await waitFor(()=>providerCalls.length===1,8000);await new Promise(r=>setTimeout(r,400));assert(providerCalls.length===1,'immediate retry detected after 429');const quotaState=(await get(local,KEYS.PROVIDER_QUOTA_STATE))[KEYS.PROVIDER_QUOTA_STATE];const family=Object.values(quotaState?.accounts||{})[0]?.families?.['seller.analytics_data.v1'];assert(family&&Number(family.next_allowed_at)>Number(family.last_provider_request_at)+65000,'Retry-After did not extend persisted due');for(const fn of alarmListeners)await fn({name:'ozon-provider-quota-wake-v1',scheduledTime:Date.now()});await new Promise(r=>setTimeout(r,200));assert(providerCalls.length===1,'alarm caused immediate 429 replay');for(const fn of startupListeners)await fn();await new Promise(r=>setTimeout(r,200));assert(providerCalls.length===1,'startup caused 429 replay');console.log('B06_429_ONE_CALL_NO_RETRY_PASS');console.log('B06_RETRY_AFTER_EXTENSION_ONLY_PASS');

console.log('REAL_OZON_REQUESTS=0');console.log('REAL_PERFORMANCE_REQUESTS=0');console.log('B06_WORKER_QUOTA_CURRENT_PASS');
